import { useState } from "react";
import {
  Grid,
  Paper,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  TablePagination,
  Popover,
  Typography,
  Box,
  Divider,
} from "@mui/material";

const data = [
  {
    Rank: "1",
    Sourceid: "28773",
    Title: "Ca-A Cancer Journal for Clinicians",
    Type: "journal",
    Issn: "15424863, 00079235",
    SJR: "106,094",
    "SJR Best Quartile": "Q1",
    "H index": "211",
    "Total Docs. (2023)": "49",
    "Total Docs. (3years)": "124",
    "Total Refs.": "4844",
    "Total Cites (3years)": "35427",
    "Citable Docs. (3years)": "89",
    "Cites / Doc. (2years)": "381,89",
    "Ref. / Doc.": "98,86",
    "%Female": "43,95",
    Overton: "2",
    SDG: "35",
    Country: "United States",
    Region: "Northern America",
    Publisher: "Wiley-Blackwell",
    Coverage: "1950-2023",
    Categories: "Hematology (Q1); Oncology (Q1)",
    Areas: "Medicine",
  },
  {
    Rank: "2",
    Sourceid: "19300156903",
    Title: "Foundations and Trends in Machine Learning",
    Type: "journal",
    Issn: "19358245, 19358237",
    SJR: "37,044",
    "SJR Best Quartile": "Q1",
    "H index": "39",
    "Total Docs. (2023)": "3",
    "Total Docs. (3years)": "13",
    "Total Refs.": "897",
    "Total Cites (3years)": "955",
    "Citable Docs. (3years)": "13",
    "Cites / Doc. (2years)": "100,11",
    "Ref. / Doc.": "299,00",
    "%Female": "27,78",
    Overton: "0",
    SDG: "0",
    Country: "United States",
    Region: "Northern America",
    Publisher: "Now Publishers Inc",
    Coverage: "2008-2023",
    Categories:
      "Artificial Intelligence (Q1); Human-Computer Interaction (Q1); Software (Q1)",
    Areas: "Computer Science",
  },
  {
    Rank: "3",
    Sourceid: "20315",
    Title: "Nature Reviews Molecular Cell Biology",
    Type: "journal",
    Issn: "14710072, 14710080",
    SJR: "35,910",
    "SJR Best Quartile": "Q1",
    "H index": "508",
    "Total Docs. (2023)": "123",
    "Total Docs. (3years)": "336",
    "Total Refs.": "11462",
    "Total Cites (3years)": "13599",
    "Citable Docs. (3years)": "153",
    "Cites / Doc. (2years)": "34,50",
    "Ref. / Doc.": "93,19",
    "%Female": "29,41",
    Overton: "1",
    SDG: "20",
    Country: "United Kingdom",
    Region: "Western Europe",
    Publisher: "Nature Publishing Group",
    Coverage: "2000-2023",
    Categories: "Cell Biology (Q1); Molecular Biology (Q1)",
    Areas: "Biochemistry, Genetics and Molecular Biology",
  },
  {
    Rank: "4",
    Sourceid: "29431",
    Title: "Quarterly Journal of Economics",
    Type: "journal",
    Issn: "00335533, 15314650",
    SJR: "30,448",
    "SJR Best Quartile": "Q1",
    "H index": "306",
    "Total Docs. (2023)": "47",
    "Total Docs. (3years)": "136",
    "Total Refs.": "3645",
    "Total Cites (3years)": "2240",
    "Citable Docs. (3years)": "136",
    "Cites / Doc. (2years)": "11,14",
    "Ref. / Doc.": "77,55",
    "%Female": "26,67",
    Overton: "35",
    SDG: "22",
    Country: "United Kingdom",
    Region: "Western Europe",
    Publisher: "Oxford University Press",
    Coverage: "1886-2023",
    Categories: "Economics and Econometrics (Q1)",
    Areas: "Economics, Econometrics and Finance",
  },
  {
    Rank: "5",
    Sourceid: "12464",
    Title: "Nature Reviews Cancer",
    Type: "journal",
    Issn: "1474175X, 14741768",
    SJR: "26,837",
    "SJR Best Quartile": "Q1",
    "H index": "505",
    "Total Docs. (2023)": "105",
    "Total Docs. (3years)": "304",
    "Total Refs.": "10805",
    "Total Cites (3years)": "10951",
    "Citable Docs. (3years)": "163",
    "Cites / Doc. (2years)": "31,23",
    "Ref. / Doc.": "102,90",
    "%Female": "44,33",
    Overton: "1",
    SDG: "59",
    Country: "United Kingdom",
    Region: "Western Europe",
    Publisher: "Nature Publishing Group",
    Coverage: "2001-2023",
    Categories: "Cancer Research (Q1); Oncology (Q1)",
    Areas: "Biochemistry, Genetics and Molecular Biology; Medicine",
  },
  {
    Rank: "6",
    Sourceid: "18434",
    Title: "Cell",
    Type: "journal",
    Issn: "00928674, 10974172",
    SJR: "24,342",
    "SJR Best Quartile": "Q1",
    "H index": "892",
    "Total Docs. (2023)": "439",
    "Total Docs. (3years)": "1496",
    "Total Refs.": "32820",
    "Total Cites (3years)": "53447",
    "Citable Docs. (3years)": "1207",
    "Cites / Doc. (2years)": "31,30",
    "Ref. / Doc.": "74,76",
    "%Female": "40,19",
    Overton: "11",
    SDG: "130",
    Country: "United States",
    Region: "Northern America",
    Publisher: "Elsevier B.V.",
    Coverage: "1974-2023",
    Categories:
      "Biochemistry, Genetics and Molecular Biology (miscellaneous) (Q1)",
    Areas: "Biochemistry, Genetics and Molecular Biology",
  },
  {
    Rank: "7",
    Sourceid: "20425",
    Title: "Nature Reviews Drug Discovery",
    Type: "journal",
    Issn: "14741784, 14741776",
    SJR: "22,399",
    "SJR Best Quartile": "Q1",
    "H index": "391",
    "Total Docs. (2023)": "239",
    "Total Docs. (3years)": "731",
    "Total Refs.": "8584",
    "Total Cites (3years)": "13091",
    "Citable Docs. (3years)": "153",
    "Cites / Doc. (2years)": "19,72",
    "Ref. / Doc.": "35,92",
    "%Female": "34,15",
    Overton: "5",
    SDG: "61",
    Country: "United Kingdom",
    Region: "Western Europe",
    Publisher: "Nature Publishing Group",
    Coverage: "2002-2023",
    Categories:
      "Drug Discovery (Q1); Medicine (miscellaneous) (Q1); Pharmacology (Q1)",
    Areas: "Medicine; Pharmacology, Toxicology and Pharmaceutics",
  },
  {
    Rank: "8",
    Sourceid: "22697",
    Title: "American Economic Review",
    Type: "journal",
    Issn: "19447981, 00028282",
    SJR: "22,344",
    "SJR Best Quartile": "Q1",
    "H index": "359",
    "Total Docs. (2023)": "95",
    "Total Docs. (3years)": "353",
    "Total Refs.": "6242",
    "Total Cites (3years)": "4811",
    "Citable Docs. (3years)": "351",
    "Cites / Doc. (2years)": "10,33",
    "Ref. / Doc.": "65,71",
    "%Female": "23,89",
    Overton: "46",
    SDG: "46",
    Country: "United States",
    Region: "Northern America",
    Publisher: "American Economic Association",
    Coverage: "1973-1975, 1978-2023",
    Categories: "Economics and Econometrics (Q1)",
    Areas: "Economics, Econometrics and Finance",
  },
  {
    Rank: "9",
    Sourceid: "21100812243",
    Title: "Nature Reviews Materials",
    Type: "journal",
    Issn: "20588437",
    SJR: "21,836",
    "SJR Best Quartile": "Q1",
    "H index": "184",
    "Total Docs. (2023)": "117",
    "Total Docs. (3years)": "335",
    "Total Refs.": "8842",
    "Total Cites (3years)": "13775",
    "Citable Docs. (3years)": "196",
    "Cites / Doc. (2years)": "31,17",
    "Ref. / Doc.": "75,57",
    "%Female": "26,86",
    Overton: "1",
    SDG: "22",
    Country: "United Kingdom",
    Region: "Western Europe",
    Publisher: "Nature Publishing Group",
    Coverage: "2016-2023",
    Categories:
      "Biomaterials (Q1); Electronic, Optical and Magnetic Materials (Q1); Energy (miscellaneous) (Q1); Materials Chemistry (Q1); Surfaces, Coatings and Films (Q1)",
    Areas: "Energy; Materials Science",
  },
  {
    Rank: "10",
    Sourceid: "17700156734",
    Title: "Nature Reviews Clinical Oncology",
    Type: "journal",
    Issn: "17594782, 17594774",
    SJR: "21,048",
    "SJR Best Quartile": "Q1",
    "H index": "217",
    "Total Docs. (2023)": "127",
    "Total Docs. (3years)": "400",
    "Total Refs.": "9888",
    "Total Cites (3years)": "10807",
    "Citable Docs. (3years)": "183",
    "Cites / Doc. (2years)": "28,36",
    "Ref. / Doc.": "77,86",
    "%Female": "38,85",
    Overton: "0",
    SDG: "56",
    Country: "United Kingdom",
    Region: "Western Europe",
    Publisher: "Nature Publishing Group",
    Coverage: "2009-2023",
    Categories: "Oncology (Q1)",
    Areas: "Medicine",
  },
  {
    Rank: "11",
    Sourceid: "15847",
    Title: "New England Journal of Medicine",
    Type: "journal",
    Issn: "00284793, 15334406",
    SJR: "20,544",
    "SJR Best Quartile": "Q1",
    "H index": "1184",
    "Total Docs. (2023)": "1388",
    "Total Docs. (3years)": "4522",
    "Total Refs.": "14603",
    "Total Cites (3years)": "107246",
    "Citable Docs. (3years)": "1824",
    "Cites / Doc. (2years)": "21,69",
    "Ref. / Doc.": "10,52",
    "%Female": "38,26",
    Overton: "0",
    SDG: "576",
    Country: "United States",
    Region: "Northern America",
    Publisher: "Massachussetts Medical Society",
    Coverage: "1945-2023",
    Categories: "Medicine (miscellaneous) (Q1)",
    Areas: "Medicine",
  },
  {
    Rank: "12",
    Sourceid: "17500",
    Title: "Journal of Finance",
    Type: "journal",
    Issn: "00221082, 15406261",
    SJR: "19,139",
    "SJR Best Quartile": "Q1",
    "H index": "352",
    "Total Docs. (2023)": "83",
    "Total Docs. (3years)": "227",
    "Total Refs.": "5043",
    "Total Cites (3years)": "1938",
    "Citable Docs. (3years)": "221",
    "Cites / Doc. (2years)": "7,00",
    "Ref. / Doc.": "60,76",
    "%Female": "16,91",
    Overton: "19",
    SDG: "19",
    Country: "United Kingdom",
    Region: "Western Europe",
    Publisher: "Wiley-Blackwell Publishing Ltd",
    Coverage: "1946-2023",
    Categories:
      "Accounting (Q1); Economics and Econometrics (Q1); Finance (Q1)",
    Areas:
      "Business, Management and Accounting; Economics, Econometrics and Finance",
  },
  {
    Rank: "13",
    Sourceid: "15819",
    Title: "Nature Medicine",
    Type: "journal",
    Issn: "1546170X, 10788956",
    SJR: "19,045",
    "SJR Best Quartile": "Q1",
    "H index": "630",
    "Total Docs. (2023)": "595",
    "Total Docs. (3years)": "1363",
    "Total Refs.": "16478",
    "Total Cites (3years)": "36243",
    "Citable Docs. (3years)": "729",
    "Cites / Doc. (2years)": "27,23",
    "Ref. / Doc.": "27,69",
    "%Female": "43,99",
    Overton: "34",
    SDG: "261",
    Country: "United Kingdom",
    Region: "Western Europe",
    Publisher: "Nature Research",
    Coverage: "1995-2023",
    Categories:
      "Biochemistry, Genetics and Molecular Biology (miscellaneous) (Q1); Medicine (miscellaneous) (Q1)",
    Areas: "Biochemistry, Genetics and Molecular Biology; Medicine",
  },
  {
    Rank: "14",
    Sourceid: "11600154092",
    Title: "Current Protocols in Bioinformatics",
    Type: "journal",
    Issn: "19343396, 1934340X",
    SJR: "18,663",
    "SJR Best Quartile": "Q1",
    "H index": "71",
    "Total Docs. (2023)": "0",
    "Total Docs. (3years)": "19",
    "Total Refs.": "0",
    "Total Cites (3years)": "963",
    "Citable Docs. (3years)": "19",
    "Cites / Doc. (2years)": "0,00",
    "Ref. / Doc.": "0,00",
    "%Female": "0,00",
    Overton: "0",
    SDG: "0",
    Country: "United States",
    Region: "Northern America",
    Publisher: "John Wiley &amp; Sons Inc.",
    Coverage: "2002-2020",
    Categories:
      "Biochemistry (Q1); Medicine (miscellaneous) (Q1); Structural Biology (Q1)",
    Areas: "Biochemistry, Genetics and Molecular Biology; Medicine",
  },
  {
    Rank: "15",
    Sourceid: "21100466539",
    Title: "MMWR supplements",
    Type: "journal",
    Issn: "23808942, 23808950",
    SJR: "18,587",
    "SJR Best Quartile": "Q1",
    "H index": "23",
    "Total Docs. (2023)": "11",
    "Total Docs. (3years)": "16",
    "Total Refs.": "0",
    "Total Cites (3years)": "802",
    "Citable Docs. (3years)": "16",
    "Cites / Doc. (2years)": "47,57",
    "Ref. / Doc.": "0,00",
    "%Female": "81,69",
    Overton: "2",
    SDG: "9",
    Country: "United States",
    Region: "Northern America",
    Publisher: "Epidemiology Program Office",
    Coverage: "2016, 2020, 2022-2023",
    Categories: "Medicine (miscellaneous) (Q1)",
    Areas: "Medicine",
  },
  {
    Rank: "16",
    Sourceid: "24404",
    Title: "Journal of Political Economy",
    Type: "journal",
    Issn: "00223808, 1537534X",
    SJR: "18,530",
    "SJR Best Quartile": "Q1",
    "H index": "215",
    "Total Docs. (2023)": "83",
    "Total Docs. (3years)": "261",
    "Total Refs.": "4493",
    "Total Cites (3years)": "2531",
    "Citable Docs. (3years)": "258",
    "Cites / Doc. (2years)": "7,04",
    "Ref. / Doc.": "54,13",
    "%Female": "17,80",
    Overton: "37",
    SDG: "28",
    Country: "United States",
    Region: "Northern America",
    Publisher: "University of Chicago",
    Coverage: "1969, 1973-1974, 1979-1985, 1987-2023",
    Categories: "Economics and Econometrics (Q1)",
    Areas: "Economics, Econometrics and Finance",
  },
  {
    Rank: "17",
    Sourceid: "21206",
    Title: "Nature",
    Type: "journal",
    Issn: "14764687, 00280836",
    SJR: "18,509",
    "SJR Best Quartile": "Q1",
    "H index": "1391",
    "Total Docs. (2023)": "3770",
    "Total Docs. (3years)": "8037",
    "Total Refs.": "74917",
    "Total Cites (3years)": "160102",
    "Citable Docs. (3years)": "3840",
    "Cites / Doc. (2years)": "19,40",
    "Ref. / Doc.": "19,87",
    "%Female": "38,12",
    Overton: "111",
    SDG: "901",
    Country: "United Kingdom",
    Region: "Western Europe",
    Publisher: "Nature Research",
    Coverage: "1869-2023",
    Categories: "Multidisciplinary (Q1)",
    Areas: "Multidisciplinary",
  },
  {
    Rank: "18",
    Sourceid: "16115",
    Title: "Nature Biotechnology",
    Type: "journal",
    Issn: "15461696, 10870156",
    SJR: "18,117",
    "SJR Best Quartile": "Q1",
    "H index": "511",
    "Total Docs. (2023)": "485",
    "Total Docs. (3years)": "1066",
    "Total Refs.": "13393",
    "Total Cites (3years)": "17008",
    "Citable Docs. (3years)": "461",
    "Cites / Doc. (2years)": "13,24",
    "Ref. / Doc.": "27,61",
    "%Female": "35,19",
    Overton: "3",
    SDG: "64",
    Country: "United Kingdom",
    Region: "Western Europe",
    Publisher: "Nature Publishing Group",
    Coverage: "1989-2023",
    Categories:
      "Applied Microbiology and Biotechnology (Q1); Bioengineering (Q1); Biomedical Engineering (Q1); Biotechnology (Q1); Molecular Medicine (Q1)",
    Areas:
      "Biochemistry, Genetics and Molecular Biology; Chemical Engineering; Engineering; Immunology and Microbiology",
  },
  {
    Rank: "19",
    Sourceid: "23340",
    Title: "Chemical Reviews",
    Type: "journal",
    Issn: "15206890, 00092665",
    SJR: "17,828",
    "SJR Best Quartile": "Q1",
    "H index": "833",
    "Total Docs. (2023)": "271",
    "Total Docs. (3years)": "851",
    "Total Refs.": "115878",
    "Total Cites (3years)": "50519",
    "Citable Docs. (3years)": "819",
    "Cites / Doc. (2years)": "49,76",
    "Ref. / Doc.": "427,59",
    "%Female": "30,50",
    Overton: "2",
    SDG: "78",
    Country: "United States",
    Region: "Northern America",
    Publisher: "American Chemical Society",
    Coverage: "1924-2023",
    Categories: "Chemistry (miscellaneous) (Q1)",
    Areas: "Chemistry",
  },
  {
    Rank: "20",
    Sourceid: "19482",
    Title: "Econometrica",
    Type: "journal",
    Issn: "00129682, 14680262",
    SJR: "17,701",
    "SJR Best Quartile": "Q1",
    "H index": "223",
    "Total Docs. (2023)": "75",
    "Total Docs. (3years)": "273",
    "Total Refs.": "3371",
    "Total Cites (3years)": "1946",
    "Citable Docs. (3years)": "268",
    "Cites / Doc. (2years)": "6,24",
    "Ref. / Doc.": "44,95",
    "%Female": "13,84",
    Overton: "0",
    SDG: "29",
    Country: "United Kingdom",
    Region: "Western Europe",
    Publisher: "Wiley-Blackwell Publishing Ltd",
    Coverage: "1974, 1977-1984, 1990-1991, 1994-2023",
    Categories: "Economics and Econometrics (Q1)",
    Areas: "Economics, Econometrics and Finance",
  },
  {
    Rank: "21",
    Sourceid: "16161",
    Title: "Review of Financial Studies",
    Type: "journal",
    Issn: "14657368, 08939454",
    SJR: "17,654",
    "SJR Best Quartile": "Q1",
    "H index": "234",
    "Total Docs. (2023)": "108",
    "Total Docs. (3years)": "410",
    "Total Refs.": "6448",
    "Total Cites (3years)": "4495",
    "Citable Docs. (3years)": "409",
    "Cites / Doc. (2years)": "8,04",
    "Ref. / Doc.": "59,70",
    "%Female": "16,43",
    Overton: "30",
    SDG: "36",
    Country: "United Kingdom",
    Region: "Western Europe",
    Publisher: "Oxford University Press",
    Coverage: "1996-2023",
    Categories:
      "Accounting (Q1); Economics and Econometrics (Q1); Finance (Q1)",
    Areas:
      "Business, Management and Accounting; Economics, Econometrics and Finance",
  },
  {
    Rank: "22",
    Sourceid: "29093",
    Title: "Cancer Cell",
    Type: "journal",
    Issn: "15356108, 18783686",
    SJR: "17,507",
    "SJR Best Quartile": "Q1",
    "H index": "398",
    "Total Docs. (2023)": "178",
    "Total Docs. (3years)": "590",
    "Total Refs.": "11546",
    "Total Cites (3years)": "12604",
    "Citable Docs. (3years)": "360",
    "Cites / Doc. (2years)": "19,83",
    "Ref. / Doc.": "64,87",
    "%Female": "41,91",
    Overton: "0",
    SDG: "157",
    Country: "United States",
    Region: "Northern America",
    Publisher: "Cell Press",
    Coverage: "2002-2023",
    Categories: "Cancer Research (Q1); Cell Biology (Q1); Oncology (Q1)",
    Areas: "Biochemistry, Genetics and Molecular Biology; Medicine",
  },
  {
    Rank: "23",
    Sourceid: "21100812579",
    Title: "Nature Energy",
    Type: "journal",
    Issn: "20587546",
    SJR: "17,497",
    "SJR Best Quartile": "Q1",
    "H index": "229",
    "Total Docs. (2023)": "229",
    "Total Docs. (3years)": "609",
    "Total Refs.": "6629",
    "Total Cites (3years)": "16808",
    "Citable Docs. (3years)": "379",
    "Cites / Doc. (2years)": "26,18",
    "Ref. / Doc.": "28,95",
    "%Female": "29,53",
    Overton: "9",
    SDG: "97",
    Country: "United States",
    Region: "Northern America",
    Publisher: "Springer Nature",
    Coverage: "2016-2023",
    Categories:
      "Electronic, Optical and Magnetic Materials (Q1); Energy Engineering and Power Technology (Q1); Fuel Technology (Q1); Renewable Energy, Sustainability and the Environment (Q1)",
    Areas: "Energy; Materials Science",
  },
  {
    Rank: "24",
    Sourceid: "18990",
    Title: "Nature Genetics",
    Type: "journal",
    Issn: "10614036, 15461718",
    SJR: "17,300",
    "SJR Best Quartile": "Q1",
    "H index": "639",
    "Total Docs. (2023)": "336",
    "Total Docs. (3years)": "654",
    "Total Refs.": "13672",
    "Total Cites (3years)": "13100",
    "Citable Docs. (3years)": "504",
    "Cites / Doc. (2years)": "19,88",
    "Ref. / Doc.": "40,69",
    "%Female": "37,01",
    Overton: "4",
    SDG: "100",
    Country: "United Kingdom",
    Region: "Western Europe",
    Publisher: "Nature Publishing Group",
    Coverage: "1992-2023",
    Categories: "Genetics (Q1)",
    Areas: "Biochemistry, Genetics and Molecular Biology",
  },
  {
    Rank: "25",
    Sourceid: "29719",
    Title: "Reviews of Modern Physics",
    Type: "journal",
    Issn: "00346861, 15390756",
    SJR: "16,061",
    "SJR Best Quartile": "Q1",
    "H index": "388",
    "Total Docs. (2023)": "36",
    "Total Docs. (3years)": "103",
    "Total Refs.": "14097",
    "Total Cites (3years)": "4303",
    "Citable Docs. (3years)": "99",
    "Cites / Doc. (2years)": "42,66",
    "Ref. / Doc.": "391,58",
    "%Female": "14,94",
    Overton: "0",
    SDG: "5",
    Country: "United States",
    Region: "Northern America",
    Publisher: "American Physical Society",
    Coverage: "1929-2023",
    Categories: "Physics and Astronomy (miscellaneous) (Q1)",
    Areas: "Physics and Astronomy",
  },
  {
    Rank: "26",
    Sourceid: "21318",
    Title: "Nature Reviews Immunology",
    Type: "journal",
    Issn: "14741741, 14741733",
    SJR: "16,009",
    "SJR Best Quartile": "Q1",
    "H index": "467",
    "Total Docs. (2023)": "169",
    "Total Docs. (3years)": "540",
    "Total Refs.": "11148",
    "Total Cites (3years)": "13815",
    "Citable Docs. (3years)": "304",
    "Cites / Doc. (2years)": "23,17",
    "Ref. / Doc.": "65,96",
    "%Female": "36,44",
    Overton: "1",
    SDG: "42",
    Country: "United Kingdom",
    Region: "Western Europe",
    Publisher: "Nature Publishing Group",
    Coverage: "2001-2023",
    Categories:
      "Immunology (Q1); Immunology and Allergy (Q1); Medicine (miscellaneous) (Q1)",
    Areas: "Immunology and Microbiology; Medicine",
  },
  {
    Rank: "27",
    Sourceid: "17900156715",
    Title: "IEEE Communications Surveys and Tutorials",
    Type: "journal",
    Issn: "1553877X",
    SJR: "15,966",
    "SJR Best Quartile": "Q1",
    "H index": "264",
    "Total Docs. (2023)": "102",
    "Total Docs. (3years)": "252",
    "Total Refs.": "19168",
    "Total Cites (3years)": "11266",
    "Citable Docs. (3years)": "244",
    "Cites / Doc. (2years)": "38,64",
    "Ref. / Doc.": "187,92",
    "%Female": "24,30",
    Overton: "0",
    SDG: "23",
    Country: "United States",
    Region: "Northern America",
    Publisher: "Institute of Electrical and Electronics Engineers Inc.",
    Coverage: "2005-2023",
    Categories: "Electrical and Electronic Engineering (Q1)",
    Areas: "Engineering",
  },
  {
    Rank: "28",
    Sourceid: "6200180159",
    Title: "World Psychiatry",
    Type: "journal",
    Issn: "17238617",
    SJR: "15,827",
    "SJR Best Quartile": "Q1",
    "H index": "140",
    "Total Docs. (2023)": "106",
    "Total Docs. (3years)": "297",
    "Total Refs.": "4359",
    "Total Cites (3years)": "4041",
    "Citable Docs. (3years)": "62",
    "Cites / Doc. (2years)": "12,99",
    "Ref. / Doc.": "41,12",
    "%Female": "41,35",
    Overton: "7",
    SDG: "13",
    Country: "United States",
    Region: "Northern America",
    Publisher: "Wiley-Blackwell",
    Coverage: "2007-2023",
    Categories: "Psychiatry and Mental Health (Q1)",
    Areas: "Medicine",
  },
  {
    Rank: "29",
    Sourceid: "20651",
    Title: "Annual Review of Immunology",
    Type: "journal",
    Issn: "15453278, 07320582",
    SJR: "15,620",
    "SJR Best Quartile": "Q1",
    "H index": "328",
    "Total Docs. (2023)": "23",
    "Total Docs. (3years)": "84",
    "Total Refs.": "4178",
    "Total Cites (3years)": "2696",
    "Citable Docs. (3years)": "83",
    "Cites / Doc. (2years)": "27,02",
    "Ref. / Doc.": "181,65",
    "%Female": "40,68",
    Overton: "0",
    SDG: "7",
    Country: "United States",
    Region: "Northern America",
    Publisher: "Annual Reviews Inc.",
    Coverage: "1983-2023",
    Categories: "Immunology (Q1); Immunology and Allergy (Q1)",
    Areas: "Immunology and Microbiology; Medicine",
  },
  {
    Rank: "30",
    Sourceid: "58530",
    Title: "National Vital Statistics Reports",
    Type: "journal",
    Issn: "15518922, 15518930",
    SJR: "14,943",
    "SJR Best Quartile": "Q1",
    "H index": "115",
    "Total Docs. (2023)": "16",
    "Total Docs. (3years)": "42",
    "Total Refs.": "403",
    "Total Cites (3years)": "896",
    "Citable Docs. (3years)": "41",
    "Cites / Doc. (2years)": "24,10",
    "Ref. / Doc.": "25,19",
    "%Female": "77,78",
    Overton: "3",
    SDG: "13",
    Country: "United States",
    Region: "Northern America",
    Publisher: "Public Health Services, US Dept of Health and Human Services",
    Coverage: "1998-2023",
    Categories: "Life-span and Life-course Studies (Q1)",
    Areas: "Social Sciences",
  },
  {
    Rank: "31",
    Sourceid: "21100778827",
    Title: "Nature Methods",
    Type: "journal",
    Issn: "15487091, 15487105",
    SJR: "14,796",
    "SJR Best Quartile": "Q1",
    "H index": "388",
    "Total Docs. (2023)": "400",
    "Total Docs. (3years)": "978",
    "Total Refs.": "11477",
    "Total Cites (3years)": "15900",
    "Citable Docs. (3years)": "588",
    "Cites / Doc. (2years)": "17,52",
    "Ref. / Doc.": "28,69",
    "%Female": "33,83",
    Overton: "2",
    SDG: "20",
    Country: "United Kingdom",
    Region: "Western Europe",
    Publisher: "Nature Publishing Group",
    Coverage: "2004-2023",
    Categories:
      "Biochemistry (Q1); Biotechnology (Q1); Cell Biology (Q1); Molecular Biology (Q1)",
    Areas: "Biochemistry, Genetics and Molecular Biology",
  },
  {
    Rank: "32",
    Sourceid: "26978",
    Title: "Advances in Physics",
    Type: "journal",
    Issn: "14606976, 00018732",
    SJR: "14,780",
    "SJR Best Quartile": "Q1",
    "H index": "123",
    "Total Docs. (2023)": "0",
    "Total Docs. (3years)": "13",
    "Total Refs.": "0",
    "Total Cites (3years)": "374",
    "Citable Docs. (3years)": "11",
    "Cites / Doc. (2years)": "12,56",
    "Ref. / Doc.": "0,00",
    "%Female": "0,00",
    Overton: "0",
    SDG: "0",
    Country: "United Kingdom",
    Region: "Western Europe",
    Publisher: "Taylor and Francis Ltd.",
    Coverage: "1952-2021, 2023",
    Categories: "Condensed Matter Physics (Q1)",
    Areas: "Physics and Astronomy",
  },
  {
    Rank: "33",
    Sourceid: "21101142543",
    Title: "Nano Research Energy",
    Type: "journal",
    Issn: "27910091, 27908119",
    SJR: "14,707",
    "SJR Best Quartile": "Q1",
    "H index": "32",
    "Total Docs. (2023)": "46",
    "Total Docs. (3years)": "35",
    "Total Refs.": "4815",
    "Total Cites (3years)": "2160",
    "Citable Docs. (3years)": "34",
    "Cites / Doc. (2years)": "61,71",
    "Ref. / Doc.": "104,67",
    "%Female": "36,44",
    Overton: "0",
    SDG: "23",
    Country: "China",
    Region: "Asiatic Region",
    Publisher: "Tsinghua University Press",
    Coverage: "2022-2023",
    Categories:
      "Chemistry (miscellaneous) (Q1); Energy (miscellaneous) (Q1); Materials Science (miscellaneous) (Q1)",
    Areas: "Chemistry; Energy; Materials Science",
  },
  {
    Rank: "34",
    Sourceid: "19434",
    Title: "MMWR Recommendations and Reports",
    Type: "journal",
    Issn: "10575987, 15458601",
    SJR: "14,618",
    "SJR Best Quartile": "Q1",
    "H index": "160",
    "Total Docs. (2023)": "70",
    "Total Docs. (3years)": "247",
    "Total Refs.": "587",
    "Total Cites (3years)": "5353",
    "Citable Docs. (3years)": "230",
    "Cites / Doc. (2years)": "21,11",
    "Ref. / Doc.": "8,39",
    "%Female": "58,79",
    Overton: "61",
    SDG: "38",
    Country: "United States",
    Region: "Northern America",
    Publisher: "Centers for Disease Control and Prevention (CDC)",
    Coverage: "1990-2023",
    Categories:
      "Epidemiology (Q1); Health Information Management (Q1); Health (social science) (Q1); Health, Toxicology and Mutagenesis (Q1); Medicine (miscellaneous) (Q1)",
    Areas:
      "Environmental Science; Health Professions; Medicine; Social Sciences",
  },
  {
    Rank: "35",
    Sourceid: "19900191906",
    Title: "Academy of Management Annals",
    Type: "journal",
    Issn: "19416520, 19416067",
    SJR: "14,605",
    "SJR Best Quartile": "Q1",
    "H index": "109",
    "Total Docs. (2023)": "23",
    "Total Docs. (3years)": "72",
    "Total Refs.": "5797",
    "Total Cites (3years)": "1938",
    "Citable Docs. (3years)": "70",
    "Cites / Doc. (2years)": "14,90",
    "Ref. / Doc.": "252,04",
    "%Female": "45,57",
    Overton: "1",
    SDG: "7",
    Country: "United States",
    Region: "Northern America",
    Publisher: "Academy of Management",
    Coverage: "2010-2023",
    Categories:
      "Business and International Management (Q1); Organizational Behavior and Human Resource Management (Q1)",
    Areas: "Business, Management and Accounting",
  },
  {
    Rank: "36",
    Sourceid: "5200152704",
    Title: "Nature Nanotechnology",
    Type: "journal",
    Issn: "17483387, 17483395",
    SJR: "14,577",
    "SJR Best Quartile": "Q1",
    "H index": "419",
    "Total Docs. (2023)": "262",
    "Total Docs. (3years)": "637",
    "Total Refs.": "10044",
    "Total Cites (3years)": "17562",
    "Citable Docs. (3years)": "466",
    "Cites / Doc. (2years)": "27,42",
    "Ref. / Doc.": "38,34",
    "%Female": "28,93",
    Overton: "0",
    SDG: "42",
    Country: "United Kingdom",
    Region: "Western Europe",
    Publisher: "Nature Publishing Group",
    Coverage: "2006-2023",
    Categories:
      "Atomic and Molecular Physics, and Optics (Q1); Bioengineering (Q1); Biomedical Engineering (Q1); Condensed Matter Physics (Q1); Electrical and Electronic Engineering (Q1); Materials Science (miscellaneous) (Q1); Nanoscience and Nanotechnology (Q1)",
    Areas:
      "Chemical Engineering; Engineering; Materials Science; Physics and Astronomy",
  },
  {
    Rank: "37",
    Sourceid: "18991",
    Title: "Nature Reviews Genetics",
    Type: "journal",
    Issn: "14710056, 14710064",
    SJR: "14,293",
    "SJR Best Quartile": "Q1",
    "H index": "421",
    "Total Docs. (2023)": "123",
    "Total Docs. (3years)": "346",
    "Total Refs.": "10202",
    "Total Cites (3years)": "6211",
    "Citable Docs. (3years)": "207",
    "Cites / Doc. (2years)": "17,40",
    "Ref. / Doc.": "82,94",
    "%Female": "32,86",
    Overton: "3",
    SDG: "15",
    Country: "United Kingdom",
    Region: "Western Europe",
    Publisher: "Nature Publishing Group",
    Coverage: "2000-2023",
    Categories:
      "Genetics (Q1); Genetics (clinical) (Q1); Molecular Biology (Q1)",
    Areas: "Biochemistry, Genetics and Molecular Biology; Medicine",
  },
  {
    Rank: "38",
    Sourceid: "17854",
    Title: "Nature Materials",
    Type: "journal",
    Issn: "14764660, 14761122",
    SJR: "14,231",
    "SJR Best Quartile": "Q1",
    "H index": "558",
    "Total Docs. (2023)": "306",
    "Total Docs. (3years)": "834",
    "Total Refs.": "9499",
    "Total Cites (3years)": "20730",
    "Citable Docs. (3years)": "593",
    "Cites / Doc. (2years)": "24,08",
    "Ref. / Doc.": "31,04",
    "%Female": "24,85",
    Overton: "0",
    SDG: "36",
    Country: "United Kingdom",
    Region: "Western Europe",
    Publisher: "Nature Publishing Group",
    Coverage: "2002-2023",
    Categories:
      "Chemistry (miscellaneous) (Q1); Condensed Matter Physics (Q1); Materials Science (miscellaneous) (Q1); Mechanical Engineering (Q1); Mechanics of Materials (Q1)",
    Areas: "Chemistry; Engineering; Materials Science; Physics and Astronomy",
  },
  {
    Rank: "39",
    Sourceid: "16036",
    Title: "Administrative Science Quarterly",
    Type: "journal",
    Issn: "00018392, 19303815",
    SJR: "14,175",
    "SJR Best Quartile": "Q1",
    "H index": "210",
    "Total Docs. (2023)": "28",
    "Total Docs. (3years)": "92",
    "Total Refs.": "3163",
    "Total Cites (3years)": "1260",
    "Citable Docs. (3years)": "86",
    "Cites / Doc. (2years)": "10,59",
    "Ref. / Doc.": "112,96",
    "%Female": "42,59",
    Overton: "0",
    SDG: "7",
    Country: "United States",
    Region: "Northern America",
    Publisher: "Johnson School at Cornell University",
    Coverage: "1975-1987, 1989-1990, 1993-1994, 1996-2023",
    Categories:
      "Arts and Humanities (miscellaneous) (Q1); Public Administration (Q1); Sociology and Political Science (Q1)",
    Areas: "Arts and Humanities; Social Sciences",
  },
  {
    Rank: "40",
    Sourceid: "28711",
    Title: "Annals of Oncology",
    Type: "journal",
    Issn: "15698041, 09237534",
    SJR: "13,942",
    "SJR Best Quartile": "Q1",
    "H index": "294",
    "Total Docs. (2023)": "144",
    "Total Docs. (3years)": "670",
    "Total Refs.": "5180",
    "Total Cites (3years)": "12698",
    "Citable Docs. (3years)": "362",
    "Cites / Doc. (2years)": "18,81",
    "Ref. / Doc.": "35,97",
    "%Female": "39,02",
    Overton: "9",
    SDG: "117",
    Country: "United Kingdom",
    Region: "Western Europe",
    Publisher: "Elsevier Ltd",
    Coverage: "1990-2023",
    Categories: "Hematology (Q1); Medicine (miscellaneous) (Q1); Oncology (Q1)",
    Areas: "Medicine",
  },
  {
    Rank: "41",
    Sourceid: "26651",
    Title: "Annual Review of Astronomy and Astrophysics",
    Type: "book series",
    Issn: "15454282, 00664146",
    SJR: "13,670",
    "SJR Best Quartile": "Q1",
    "H index": "210",
    "Total Docs. (2023)": "14",
    "Total Docs. (3years)": "42",
    "Total Refs.": "3772",
    "Total Cites (3years)": "1271",
    "Citable Docs. (3years)": "39",
    "Cites / Doc. (2years)": "23,96",
    "Ref. / Doc.": "269,43",
    "%Female": "26,09",
    Overton: "0",
    SDG: "1",
    Country: "United States",
    Region: "Northern America",
    Publisher: "Annual Reviews Inc.",
    Coverage: "1990-2023",
    Categories:
      "Astronomy and Astrophysics (Q1); Space and Planetary Science (Q1)",
    Areas: "Earth and Planetary Sciences; Physics and Astronomy",
  },
  {
    Rank: "42",
    Sourceid: "24379",
    Title: "Journal of Financial Economics",
    Type: "journal",
    Issn: "0304405X",
    SJR: "13,655",
    "SJR Best Quartile": "Q1",
    "H index": "311",
    "Total Docs. (2023)": "89",
    "Total Docs. (3years)": "563",
    "Total Refs.": "4857",
    "Total Cites (3years)": "6315",
    "Citable Docs. (3years)": "559",
    "Cites / Doc. (2years)": "11,14",
    "Ref. / Doc.": "54,57",
    "%Female": "23,11",
    Overton: "12",
    SDG: "29",
    Country: "Netherlands",
    Region: "Western Europe",
    Publisher: "Elsevier B.V.",
    Coverage: "1974-2023",
    Categories:
      "Accounting (Q1); Economics and Econometrics (Q1); Finance (Q1); Strategy and Management (Q1)",
    Areas:
      "Business, Management and Accounting; Economics, Econometrics and Finance",
  },
  {
    Rank: "43",
    Sourceid: "24202",
    Title: "Review of Economic Studies",
    Type: "journal",
    Issn: "00346527, 1467937X",
    SJR: "13,609",
    "SJR Best Quartile": "Q1",
    "H index": "165",
    "Total Docs. (2023)": "93",
    "Total Docs. (3years)": "250",
    "Total Refs.": "5332",
    "Total Cites (3years)": "1699",
    "Citable Docs. (3years)": "250",
    "Cites / Doc. (2years)": "6,02",
    "Ref. / Doc.": "57,33",
    "%Female": "15,88",
    Overton: "55",
    SDG: "46",
    Country: "United Kingdom",
    Region: "Western Europe",
    Publisher: "Oxford University Press",
    Coverage: "1933-1974, 1976-2023",
    Categories: "Economics and Econometrics (Q1)",
    Areas: "Economics, Econometrics and Finance",
  },
  {
    Rank: "44",
    Sourceid: "20798",
    Title: "Immunity",
    Type: "journal",
    Issn: "10974180, 10747613",
    SJR: "13,578",
    "SJR Best Quartile": "Q1",
    "H index": "455",
    "Total Docs. (2023)": "233",
    "Total Docs. (3years)": "688",
    "Total Refs.": "15608",
    "Total Cites (3years)": "13409",
    "Citable Docs. (3years)": "550",
    "Cites / Doc. (2years)": "16,89",
    "Ref. / Doc.": "66,99",
    "%Female": "40,35",
    Overton: "1",
    SDG: "95",
    Country: "United States",
    Region: "Northern America",
    Publisher: "Cell Press",
    Coverage: "1994-2023",
    Categories:
      "Immunology (Q1); Immunology and Allergy (Q1); Infectious Diseases (Q1)",
    Areas: "Immunology and Microbiology; Medicine",
  },
  {
    Rank: "45",
    Sourceid: "21100862548",
    Title: "Nature Catalysis",
    Type: "journal",
    Issn: "25201158",
    SJR: "13,315",
    "SJR Best Quartile": "Q1",
    "H index": "136",
    "Total Docs. (2023)": "180",
    "Total Docs. (3years)": "471",
    "Total Refs.": "6682",
    "Total Cites (3years)": "12109",
    "Citable Docs. (3years)": "368",
    "Cites / Doc. (2years)": "24,27",
    "Ref. / Doc.": "37,12",
    "%Female": "26,28",
    Overton: "0",
    SDG: "47",
    Country: "United States",
    Region: "Northern America",
    Publisher: "Nature Publishing Group",
    Coverage: "2018-2023",
    Categories:
      "Biochemistry (Q1); Bioengineering (Q1); Catalysis (Q1); Process Chemistry and Technology (Q1)",
    Areas: "Biochemistry, Genetics and Molecular Biology; Chemical Engineering",
  },
  {
    Rank: "46",
    Sourceid: "110092",
    Title: "Morbidity and Mortality Weekly Report",
    Type: "journal",
    Issn: "01492195, 1545861X",
    SJR: "13,080",
    "SJR Best Quartile": "Q1",
    "H index": "260",
    "Total Docs. (2023)": "243",
    "Total Docs. (3years)": "827",
    "Total Refs.": "1865",
    "Total Cites (3years)": "14374",
    "Citable Docs. (3years)": "679",
    "Cites / Doc. (2years)": "16,58",
    "Ref. / Doc.": "7,67",
    "%Female": "62,53",
    Overton: "162",
    SDG: "124",
    Country: "United States",
    Region: "Northern America",
    Publisher: "Department of Health and Human Services",
    Coverage: "1981-2023",
    Categories:
      "Epidemiology (Q1); Health Information Management (Q1); Health (social science) (Q1); Health, Toxicology and Mutagenesis (Q1); Medicine (miscellaneous) (Q1)",
    Areas:
      "Environmental Science; Health Professions; Medicine; Social Sciences",
  },
  {
    Rank: "47",
    Sourceid: "23350",
    Title: "Chemical Society Reviews",
    Type: "journal",
    Issn: "03060012, 14604744",
    SJR: "12,511",
    "SJR Best Quartile": "Q1",
    "H index": "635",
    "Total Docs. (2023)": "252",
    "Total Docs. (3years)": "983",
    "Total Refs.": "61439",
    "Total Cites (3years)": "44032",
    "Citable Docs. (3years)": "979",
    "Cites / Doc. (2years)": "38,71",
    "Ref. / Doc.": "243,81",
    "%Female": "32,40",
    Overton: "0",
    SDG: "81",
    Country: "United Kingdom",
    Region: "Western Europe",
    Publisher: "Royal Society of Chemistry",
    Coverage: "1972-2023",
    Categories: "Chemistry (miscellaneous) (Q1)",
    Areas: "Chemistry",
  },
  {
    Rank: "48",
    Sourceid: "19900191885",
    Title: "American Economic Journal: Macroeconomics",
    Type: "journal",
    Issn: "19457707, 19457715",
    SJR: "12,324",
    "SJR Best Quartile": "Q1",
    "H index": "81",
    "Total Docs. (2023)": "55",
    "Total Docs. (3years)": "137",
    "Total Refs.": "2838",
    "Total Cites (3years)": "862",
    "Citable Docs. (3years)": "137",
    "Cites / Doc. (2years)": "6,20",
    "Ref. / Doc.": "51,60",
    "%Female": "17,36",
    Overton: "26",
    SDG: "35",
    Country: "United States",
    Region: "Northern America",
    Publisher: "American Economic Association",
    Coverage: "2009-2023",
    Categories: "Economics, Econometrics and Finance (miscellaneous) (Q1)",
    Areas: "Economics, Econometrics and Finance",
  },
  {
    Rank: "49",
    Sourceid: "21101089342",
    Title: "Nature Reviews Methods Primers",
    Type: "journal",
    Issn: "26628449",
    SJR: "12,294",
    "SJR Best Quartile": "Q1",
    "H index": "46",
    "Total Docs. (2023)": "62",
    "Total Docs. (3years)": "154",
    "Total Refs.": "8174",
    "Total Cites (3years)": "4174",
    "Citable Docs. (3years)": "86",
    "Cites / Doc. (2years)": "27,10",
    "Ref. / Doc.": "131,84",
    "%Female": "31,14",
    Overton: "0",
    SDG: "10",
    Country: "United States",
    Region: "Northern America",
    Publisher: "Springer Nature",
    Coverage: "2021-2023",
    Categories:
      "Biochemistry, Genetics and Molecular Biology (miscellaneous) (Q1); Medicine (miscellaneous) (Q1)",
    Areas: "Biochemistry, Genetics and Molecular Biology; Medicine",
  },
  {
    Rank: "50",
    Sourceid: "21101141505",
    Title: "eScience",
    Type: "journal",
    Issn: "20972431, 26671417",
    SJR: "12,288",
    "SJR Best Quartile": "Q1",
    "H index": "44",
    "Total Docs. (2023)": "60",
    "Total Docs. (3years)": "79",
    "Total Refs.": "4858",
    "Total Cites (3years)": "3323",
    "Citable Docs. (3years)": "78",
    "Cites / Doc. (2years)": "42,06",
    "Ref. / Doc.": "80,97",
    "%Female": "33,06",
    Overton: "0",
    SDG: "35",
    Country: "China",
    Region: "Asiatic Region",
    Publisher: "KeAi Communications Co.",
    Coverage: "2021-2023",
    Categories:
      "Electrochemistry (Q1); Materials Chemistry (Q1); Renewable Energy, Sustainability and the Environment (Q1)",
    Areas: "Chemistry; Energy; Materials Science",
  },
  {
    Rank: "51",
    Sourceid: "110561",
    Title:
      "Proceedings of the IEEE International Conference on Computer Vision",
    Type: "conference and proceedings",
    Issn: "15505499",
    SJR: "12,263",
    "SJR Best Quartile": "-",
    "H index": "356",
    "Total Docs. (2023)": "1607",
    "Total Docs. (3years)": "1987",
    "Total Refs.": "91756",
    "Total Cites (3years)": "38161",
    "Citable Docs. (3years)": "1983",
    "Cites / Doc. (2years)": "19,21",
    "Ref. / Doc.": "57,10",
    "%Female": "25,95",
    Overton: "0",
    SDG: "38",
    Country: "United States",
    Region: "Northern America",
    Publisher: "Institute of Electrical and Electronics Engineers Inc.",
    Coverage:
      "1988, 1995, 1998-1999, 2001, 2003, 2005, 2007, 2009, 2011, 2013, 2015-2017, 2019, 2021",
    Categories: "Computer Vision and Pattern Recognition; Software",
    Areas: "Computer Science",
  },
  {
    Rank: "52",
    Sourceid: "17436",
    Title: "Nature Neuroscience",
    Type: "journal",
    Issn: "10976256, 15461726",
    SJR: "12,261",
    "SJR Best Quartile": "Q1",
    "H index": "479",
    "Total Docs. (2023)": "281",
    "Total Docs. (3years)": "622",
    "Total Refs.": "12439",
    "Total Cites (3years)": "10101",
    "Citable Docs. (3years)": "497",
    "Cites / Doc. (2years)": "14,93",
    "Ref. / Doc.": "44,27",
    "%Female": "39,09",
    Overton: "2",
    SDG: "13",
    Country: "United Kingdom",
    Region: "Western Europe",
    Publisher: "Nature Research",
    Coverage: "1998-2023",
    Categories: "Neuroscience (miscellaneous) (Q1)",
    Areas: "Neuroscience",
  },
  {
    Rank: "53",
    Sourceid: "17700155014",
    Title: "Handbook of Econometrics",
    Type: "book series",
    Issn: "15734412",
    SJR: "12,192",
    "SJR Best Quartile": "Q1",
    "H index": "24",
    "Total Docs. (2023)": "0",
    "Total Docs. (3years)": "6",
    "Total Refs.": "0",
    "Total Cites (3years)": "40",
    "Citable Docs. (3years)": "6",
    "Cites / Doc. (2years)": "0,00",
    "Ref. / Doc.": "0,00",
    "%Female": "0,00",
    Overton: "0",
    SDG: "0",
    Country: "Netherlands",
    Region: "Western Europe",
    Publisher: "Elsevier B.V.",
    Coverage: "1983-1984, 1986, 1994, 2001, 2007, 2020",
    Categories: "Economics and Econometrics (Q1)",
    Areas: "Economics, Econometrics and Finance",
  },
  {
    Rank: "54",
    Sourceid: "12354",
    Title: "Lancet Oncology, The",
    Type: "journal",
    Issn: "14702045, 14745488",
    SJR: "12,179",
    "SJR Best Quartile": "Q1",
    "H index": "408",
    "Total Docs. (2023)": "393",
    "Total Docs. (3years)": "1455",
    "Total Refs.": "5354",
    "Total Cites (3years)": "17873",
    "Citable Docs. (3years)": "634",
    "Cites / Doc. (2years)": "11,39",
    "Ref. / Doc.": "13,62",
    "%Female": "42,77",
    Overton: "0",
    SDG: "289",
    Country: "United Kingdom",
    Region: "Western Europe",
    Publisher: "Elsevier Ltd",
    Coverage: "2000-2023",
    Categories: "Oncology (Q1)",
    Areas: "Medicine",
  },
  {
    Rank: "55",
    Sourceid: "16590",
    Title: "Lancet, The",
    Type: "journal",
    Issn: "01406736, 1474547X",
    SJR: "12,113",
    "SJR Best Quartile": "Q1",
    "H index": "895",
    "Total Docs. (2023)": "1398",
    "Total Docs. (3years)": "4046",
    "Total Refs.": "22192",
    "Total Cites (3years)": "65313",
    "Citable Docs. (3years)": "1370",
    "Cites / Doc. (2years)": "14,35",
    "Ref. / Doc.": "15,87",
    "%Female": "51,49",
    Overton: "0",
    SDG: "490",
    Country: "United Kingdom",
    Region: "Western Europe",
    Publisher: "Elsevier B.V.",
    Coverage: "1823-2023",
    Categories: "Medicine (miscellaneous) (Q1)",
    Areas: "Medicine",
  },
  {
    Rank: "56",
    Sourceid: "23571",
    Title: "Science",
    Type: "journal",
    Issn: "10959203, 00368075",
    SJR: "11,902",
    "SJR Best Quartile": "Q1",
    "H index": "1336",
    "Total Docs. (2023)": "2181",
    "Total Docs. (3years)": "8261",
    "Total Refs.": "42348",
    "Total Cites (3years)": "117779",
    "Citable Docs. (3years)": "4229",
    "Cites / Doc. (2years)": "13,46",
    "Ref. / Doc.": "19,42",
    "%Female": "33,89",
    Overton: "48",
    SDG: "328",
    Country: "United States",
    Region: "Northern America",
    Publisher: "American Association for the Advancement of Science",
    Coverage: "1880-1881, 1883-2023",
    Categories:
      "History and Philosophy of Science (Q1); Multidisciplinary (Q1)",
    Areas: "Arts and Humanities; Multidisciplinary",
  },
  {
    Rank: "57",
    Sourceid: "21101023100",
    Title: "Nature Cancer",
    Type: "journal",
    Issn: "26621347",
    SJR: "11,900",
    "SJR Best Quartile": "Q1",
    "H index": "61",
    "Total Docs. (2023)": "176",
    "Total Docs. (3years)": "453",
    "Total Refs.": "7513",
    "Total Cites (3years)": "5933",
    "Citable Docs. (3years)": "297",
    "Cites / Doc. (2years)": "12,27",
    "Ref. / Doc.": "42,69",
    "%Female": "43,45",
    Overton: "0",
    SDG: "102",
    Country: "United States",
    Region: "Northern America",
    Publisher: "Nature Research",
    Coverage: "2020-2023",
    Categories: "Cancer Research (Q1); Oncology (Q1)",
    Areas: "Biochemistry, Genetics and Molecular Biology; Medicine",
  },
  {
    Rank: "58",
    Sourceid: "22951",
    Title: "Journal of Marketing",
    Type: "journal",
    Issn: "15477185, 00222429",
    SJR: "11,799",
    "SJR Best Quartile": "Q1",
    "H index": "284",
    "Total Docs. (2023)": "56",
    "Total Docs. (3years)": "173",
    "Total Refs.": "4217",
    "Total Cites (3years)": "2865",
    "Citable Docs. (3years)": "152",
    "Cites / Doc. (2years)": "15,09",
    "Ref. / Doc.": "75,30",
    "%Female": "37,57",
    Overton: "0",
    SDG: "4",
    Country: "United States",
    Region: "Northern America",
    Publisher: "American Marketing Association",
    Coverage: "1969, 1971, 1973, 1977, 1979-1981, 1995-2023",
    Categories:
      "Business and International Management (Q1); Economics and Econometrics (Q1); Marketing (Q1)",
    Areas:
      "Business, Management and Accounting; Economics, Econometrics and Finance",
  },
  {
    Rank: "59",
    Sourceid: "11300153736",
    Title: "Annual Review of Pathology: Mechanisms of Disease",
    Type: "journal",
    Issn: "15534006, 15534014",
    SJR: "11,748",
    "SJR Best Quartile": "Q1",
    "H index": "147",
    "Total Docs. (2023)": "22",
    "Total Docs. (3years)": "63",
    "Total Refs.": "3087",
    "Total Cites (3years)": "2361",
    "Citable Docs. (3years)": "63",
    "Cites / Doc. (2years)": "28,74",
    "Ref. / Doc.": "140,32",
    "%Female": "33,33",
    Overton: "0",
    SDG: "15",
    Country: "United States",
    Region: "Northern America",
    Publisher: "Annual Reviews Inc.",
    Coverage: "2006-2023",
    Categories:
      "Medicine (miscellaneous) (Q1); Pathology and Forensic Medicine (Q1); Plant Science (Q1)",
    Areas: "Agricultural and Biological Sciences; Medicine",
  },
  {
    Rank: "60",
    Sourceid: "21100834904",
    Title: "Joule",
    Type: "journal",
    Issn: "25424351",
    SJR: "11,724",
    "SJR Best Quartile": "Q1",
    "H index": "187",
    "Total Docs. (2023)": "218",
    "Total Docs. (3years)": "681",
    "Total Refs.": "10656",
    "Total Cites (3years)": "18624",
    "Citable Docs. (3years)": "525",
    "Cites / Doc. (2years)": "25,40",
    "Ref. / Doc.": "48,88",
    "%Female": "25,06",
    Overton: "7",
    SDG: "150",
    Country: "United States",
    Region: "Northern America",
    Publisher: "Cell Press",
    Coverage: "2017-2023",
    Categories: "Energy (miscellaneous) (Q1)",
    Areas: "Energy",
  },
  {
    Rank: "61",
    Sourceid: "21100884663",
    Title: "Nature Electronics",
    Type: "journal",
    Issn: "25201131",
    SJR: "11,667",
    "SJR Best Quartile": "Q1",
    "H index": "109",
    "Total Docs. (2023)": "196",
    "Total Docs. (3years)": "507",
    "Total Refs.": "5029",
    "Total Cites (3years)": "9336",
    "Citable Docs. (3years)": "303",
    "Cites / Doc. (2years)": "16,04",
    "Ref. / Doc.": "25,66",
    "%Female": "24,33",
    Overton: "1",
    SDG: "10",
    Country: "United Kingdom",
    Region: "Western Europe",
    Publisher: "Nature Publishing Group",
    Coverage: "2018-2023",
    Categories:
      "Electrical and Electronic Engineering (Q1); Electronic, Optical and Magnetic Materials (Q1); Instrumentation (Q1)",
    Areas: "Engineering; Materials Science; Physics and Astronomy",
  },
  {
    Rank: "62",
    Sourceid: "21100826569",
    Title: "Nature Reviews Chemistry",
    Type: "journal",
    Issn: "23973358",
    SJR: "11,603",
    "SJR Best Quartile": "Q1",
    "H index": "109",
    "Total Docs. (2023)": "107",
    "Total Docs. (3years)": "283",
    "Total Refs.": "7360",
    "Total Cites (3years)": "5690",
    "Citable Docs. (3years)": "172",
    "Cites / Doc. (2years)": "19,84",
    "Ref. / Doc.": "68,79",
    "%Female": "25,58",
    Overton: "0",
    SDG: "8",
    Country: "United Kingdom",
    Region: "Western Europe",
    Publisher: "Nature Publishing Group",
    Coverage: "2017-2023",
    Categories:
      "Chemical Engineering (miscellaneous) (Q1); Chemistry (miscellaneous) (Q1)",
    Areas: "Chemical Engineering; Chemistry",
  },
  {
    Rank: "63",
    Sourceid: "146172",
    Title: "Cell Metabolism",
    Type: "journal",
    Issn: "15504131, 19327420",
    SJR: "11,406",
    "SJR Best Quartile": "Q1",
    "H index": "345",
    "Total Docs. (2023)": "182",
    "Total Docs. (3years)": "608",
    "Total Refs.": "11807",
    "Total Cites (3years)": "12494",
    "Citable Docs. (3years)": "489",
    "Cites / Doc. (2years)": "18,60",
    "Ref. / Doc.": "64,87",
    "%Female": "41,80",
    Overton: "0",
    SDG: "86",
    Country: "United States",
    Region: "Northern America",
    Publisher: "Cell Press",
    Coverage: "2005-2023",
    Categories: "Cell Biology (Q1); Molecular Biology (Q1); Physiology (Q1)",
    Areas: "Biochemistry, Genetics and Molecular Biology",
  },
  {
    Rank: "64",
    Sourceid: "21315",
    Title: "Nature Immunology",
    Type: "journal",
    Issn: "15292908, 15292916",
    SJR: "11,274",
    "SJR Best Quartile": "Q1",
    "H index": "440",
    "Total Docs. (2023)": "303",
    "Total Docs. (3years)": "771",
    "Total Refs.": "10345",
    "Total Cites (3years)": "10949",
    "Citable Docs. (3years)": "529",
    "Cites / Doc. (2years)": "13,85",
    "Ref. / Doc.": "34,14",
    "%Female": "44,58",
    Overton: "0",
    SDG: "96",
    Country: "United Kingdom",
    Region: "Western Europe",
    Publisher: "Nature Publishing Group",
    Coverage: "2000-2023",
    Categories: "Immunology (Q1); Immunology and Allergy (Q1)",
    Areas: "Immunology and Microbiology; Medicine",
  },
  {
    Rank: "65",
    Sourceid: "5700165152",
    Title: "Nature Photonics",
    Type: "journal",
    Issn: "17494885",
    SJR: "11,249",
    "SJR Best Quartile": "Q1",
    "H index": "385",
    "Total Docs. (2023)": "209",
    "Total Docs. (3years)": "516",
    "Total Refs.": "6870",
    "Total Cites (3years)": "10826",
    "Citable Docs. (3years)": "362",
    "Cites / Doc. (2years)": "19,59",
    "Ref. / Doc.": "32,87",
    "%Female": "20,68",
    Overton: "0",
    SDG: "19",
    Country: "United Kingdom",
    Region: "Western Europe",
    Publisher: "Nature Publishing Group",
    Coverage: "2007-2023",
    Categories:
      "Atomic and Molecular Physics, and Optics (Q1); Electronic, Optical and Magnetic Materials (Q1)",
    Areas: "Materials Science; Physics and Astronomy",
  },
  {
    Rank: "66",
    Sourceid: "27165",
    Title: "Journal of Economic Literature",
    Type: "journal",
    Issn: "00220515",
    SJR: "11,092",
    "SJR Best Quartile": "Q1",
    "H index": "180",
    "Total Docs. (2023)": "36",
    "Total Docs. (3years)": "76",
    "Total Refs.": "4802",
    "Total Cites (3years)": "1055",
    "Citable Docs. (3years)": "75",
    "Cites / Doc. (2years)": "12,18",
    "Ref. / Doc.": "133,39",
    "%Female": "35,80",
    Overton: "19",
    SDG: "20",
    Country: "United States",
    Region: "Northern America",
    Publisher: "American Economic Association",
    Coverage: "1981, 1984, 1986, 1996-2023",
    Categories: "Economics and Econometrics (Q1)",
    Areas: "Economics, Econometrics and Finance",
  },
  {
    Rank: "67",
    Sourceid: "17500155114",
    Title: "Energy and Environmental Science",
    Type: "journal",
    Issn: "17545692, 17545706",
    SJR: "10,935",
    "SJR Best Quartile": "Q1",
    "H index": "436",
    "Total Docs. (2023)": "461",
    "Total Docs. (3years)": "1124",
    "Total Refs.": "37113",
    "Total Cites (3years)": "36095",
    "Citable Docs. (3years)": "1117",
    "Cites / Doc. (2years)": "30,56",
    "Ref. / Doc.": "80,51",
    "%Female": "29,72",
    Overton: "2",
    SDG: "302",
    Country: "United Kingdom",
    Region: "Western Europe",
    Publisher: "Royal Society of Chemistry",
    Coverage: "2008-2023",
    Categories:
      "Environmental Chemistry (Q1); Nuclear Energy and Engineering (Q1); Pollution (Q1); Renewable Energy, Sustainability and the Environment (Q1)",
    Areas: "Energy; Environmental Science",
  },
  {
    Rank: "68",
    Sourceid: "24004",
    Title: "Physiological Reviews",
    Type: "journal",
    Issn: "15221210, 00319333",
    SJR: "10,821",
    "SJR Best Quartile": "Q1",
    "H index": "388",
    "Total Docs. (2023)": "51",
    "Total Docs. (3years)": "129",
    "Total Refs.": "21543",
    "Total Cites (3years)": "4032",
    "Citable Docs. (3years)": "119",
    "Cites / Doc. (2years)": "31,12",
    "Ref. / Doc.": "422,41",
    "%Female": "37,79",
    Overton: "0",
    SDG: "16",
    Country: "United States",
    Region: "Northern America",
    Publisher: "American Physiological Society",
    Coverage: "1945-2023",
    Categories:
      "Medicine (miscellaneous) (Q1); Molecular Biology (Q1); Physiology (Q1); Physiology (medical) (Q1)",
    Areas: "Biochemistry, Genetics and Molecular Biology; Medicine",
  },
  {
    Rank: "69",
    Sourceid: "29949",
    Title: "Journal of Clinical Oncology",
    Type: "journal",
    Issn: "15277755, 0732183X",
    SJR: "10,639",
    "SJR Best Quartile": "Q1",
    "H index": "624",
    "Total Docs. (2023)": "783",
    "Total Docs. (3years)": "1664",
    "Total Refs.": "20976",
    "Total Cites (3years)": "26011",
    "Citable Docs. (3years)": "1205",
    "Cites / Doc. (2years)": "13,64",
    "Ref. / Doc.": "26,79",
    "%Female": "41,81",
    Overton: "0",
    SDG: "539",
    Country: "United States",
    Region: "Northern America",
    Publisher: "Lippincott Williams and Wilkins Ltd.",
    Coverage: "1983-2023",
    Categories:
      "Cancer Research (Q1); Medicine (miscellaneous) (Q1); Oncology (Q1)",
    Areas: "Biochemistry, Genetics and Molecular Biology; Medicine",
  },
  {
    Rank: "70",
    Sourceid: "20206",
    Title: "Academy of Management Review",
    Type: "journal",
    Issn: "03637425",
    SJR: "10,486",
    "SJR Best Quartile": "Q1",
    "H index": "306",
    "Total Docs. (2023)": "43",
    "Total Docs. (3years)": "146",
    "Total Refs.": "4234",
    "Total Cites (3years)": "2361",
    "Citable Docs. (3years)": "137",
    "Cites / Doc. (2years)": "17,09",
    "Ref. / Doc.": "98,47",
    "%Female": "25,00",
    Overton: "0",
    SDG: "4",
    Country: "United States",
    Region: "Northern America",
    Publisher: "Academy of Management",
    Coverage: "1978-1987, 1989-1991, 1996-2023",
    Categories:
      "Business, Management and Accounting (miscellaneous) (Q1); Management of Technology and Innovation (Q1); Strategy and Management (Q1)",
    Areas: "Business, Management and Accounting",
  },
  {
    Rank: "71",
    Sourceid: "24212",
    Title:
      "Proceedings of the IEEE Computer Society Conference on Computer Vision and Pattern Recognition",
    Type: "conference and proceedings",
    Issn: "10636919",
    SJR: "10,331",
    "SJR Best Quartile": "-",
    "H index": "531",
    "Total Docs. (2023)": "1613",
    "Total Docs. (3years)": "5199",
    "Total Refs.": "91574",
    "Total Cites (3years)": "135771",
    "Citable Docs. (3years)": "5194",
    "Cites / Doc. (2years)": "21,76",
    "Ref. / Doc.": "56,77",
    "%Female": "24,99",
    Overton: "0",
    SDG: "29",
    Country: "United States",
    Region: "Northern America",
    Publisher: "IEEE Computer Society",
    Coverage: "1992, 1994, 1996-2001, 2003-2004, 2006-2007, 2010-2022",
    Categories: "Computer Vision and Pattern Recognition; Software",
    Areas: "Computer Science",
  },
  {
    Rank: "72",
    Sourceid: "71056",
    Title: "MMWR Surveillance Summaries",
    Type: "journal",
    Issn: "15458636, 15460738",
    SJR: "10,275",
    "SJR Best Quartile": "Q1",
    "H index": "121",
    "Total Docs. (2023)": "9",
    "Total Docs. (3years)": "113",
    "Total Refs.": "401",
    "Total Cites (3years)": "2441",
    "Citable Docs. (3years)": "102",
    "Cites / Doc. (2years)": "21,97",
    "Ref. / Doc.": "44,56",
    "%Female": "75,00",
    Overton: "4",
    SDG: "9",
    Country: "United States",
    Region: "Northern America",
    Publisher: "Centers for Disease Control and Prevention (CDC)",
    Coverage: "2002-2023",
    Categories:
      "Epidemiology (Q1); Health Information Management (Q1); Health (social science) (Q1); Health, Toxicology and Mutagenesis (Q1)",
    Areas:
      "Environmental Science; Health Professions; Medicine; Social Sciences",
  },
  {
    Rank: "73",
    Sourceid: "6100153018",
    Title: "Cell Stem Cell",
    Type: "journal",
    Issn: "19345909, 18759777",
    SJR: "10,253",
    "SJR Best Quartile": "Q1",
    "H index": "305",
    "Total Docs. (2023)": "151",
    "Total Docs. (3years)": "548",
    "Total Refs.": "9041",
    "Total Cites (3years)": "7464",
    "Citable Docs. (3years)": "425",
    "Cites / Doc. (2years)": "12,46",
    "Ref. / Doc.": "59,87",
    "%Female": "41,05",
    Overton: "1",
    SDG: "34",
    Country: "United States",
    Region: "Northern America",
    Publisher: "Cell Press",
    Coverage: "2007-2023",
    Categories: "Cell Biology (Q1); Genetics (Q1); Molecular Medicine (Q1)",
    Areas: "Biochemistry, Genetics and Molecular Biology",
  },
  {
    Rank: "74",
    Sourceid: "21100237403",
    Title: "Lancet Diabetes and Endocrinology,The",
    Type: "journal",
    Issn: "22138595, 22138587",
    SJR: "10,247",
    "SJR Best Quartile": "Q1",
    "H index": "173",
    "Total Docs. (2023)": "194",
    "Total Docs. (3years)": "575",
    "Total Refs.": "4605",
    "Total Cites (3years)": "7030",
    "Citable Docs. (3years)": "222",
    "Cites / Doc. (2years)": "12,48",
    "Ref. / Doc.": "23,74",
    "%Female": "41,98",
    Overton: "0",
    SDG: "122",
    Country: "United Kingdom",
    Region: "Western Europe",
    Publisher: "Elsevier Ltd",
    Coverage: "2013-2023",
    Categories:
      "Endocrinology (Q1); Endocrinology, Diabetes and Metabolism (Q1); Internal Medicine (Q1)",
    Areas: "Biochemistry, Genetics and Molecular Biology; Medicine",
  },
  {
    Rank: "75",
    Sourceid: "21100780831",
    Title: "Nature Reviews Disease Primers",
    Type: "journal",
    Issn: "2056676X",
    SJR: "10,215",
    "SJR Best Quartile": "Q1",
    "H index": "186",
    "Total Docs. (2023)": "69",
    "Total Docs. (3years)": "274",
    "Total Refs.": "7205",
    "Total Cites (3years)": "7476",
    "Citable Docs. (3years)": "189",
    "Cites / Doc. (2years)": "24,62",
    "Ref. / Doc.": "104,42",
    "%Female": "39,71",
    Overton: "1",
    SDG: "25",
    Country: "United Kingdom",
    Region: "Western Europe",
    Publisher: "Nature Publishing Group",
    Coverage: "2015-2023",
    Categories: "Medicine (miscellaneous) (Q1)",
    Areas: "Medicine",
  },
  {
    Rank: "76",
    Sourceid: "28677",
    Title: "Living Reviews in Relativity",
    Type: "journal",
    Issn: "14338351, 23673613",
    SJR: "10,188",
    "SJR Best Quartile": "Q1",
    "H index": "93",
    "Total Docs. (2023)": "5",
    "Total Docs. (3years)": "14",
    "Total Refs.": "4669",
    "Total Cites (3years)": "473",
    "Citable Docs. (3years)": "14",
    "Cites / Doc. (2years)": "25,80",
    "Ref. / Doc.": "933,80",
    "%Female": "25,50",
    Overton: "0",
    SDG: "0",
    Country: "Switzerland",
    Region: "Western Europe",
    Publisher: "Springer International Publishing AG",
    Coverage: "1998-2023",
    Categories: "Physics and Astronomy (miscellaneous) (Q1)",
    Areas: "Physics and Astronomy",
  },
  {
    Rank: "77",
    Sourceid: "13969",
    Title: "Psychological Science in the Public Interest",
    Type: "journal",
    Issn: "21600031, 15291006",
    SJR: "9,887",
    "SJR Best Quartile": "Q1",
    "H index": "60",
    "Total Docs. (2023)": "10",
    "Total Docs. (3years)": "21",
    "Total Refs.": "1051",
    "Total Cites (3years)": "450",
    "Citable Docs. (3years)": "12",
    "Cites / Doc. (2years)": "10,36",
    "Ref. / Doc.": "105,10",
    "%Female": "61,54",
    Overton: "0",
    SDG: "4",
    Country: "United States",
    Region: "Northern America",
    Publisher: "SAGE Publications Inc.",
    Coverage: "2000-2023",
    Categories: "Psychology (miscellaneous) (Q1)",
    Areas: "Psychology",
  },
  {
    Rank: "78",
    Sourceid: "25297",
    Title: "Journal of Hepatology",
    Type: "journal",
    Issn: "16000641, 01688278",
    SJR: "9,857",
    "SJR Best Quartile": "Q1",
    "H index": "301",
    "Total Docs. (2023)": "426",
    "Total Docs. (3years)": "1327",
    "Total Refs.": "15192",
    "Total Cites (3years)": "18226",
    "Citable Docs. (3years)": "685",
    "Cites / Doc. (2years)": "12,66",
    "Ref. / Doc.": "35,66",
    "%Female": "36,89",
    Overton: "5",
    SDG: "187",
    Country: "Netherlands",
    Region: "Western Europe",
    Publisher: "Elsevier B.V.",
    Coverage: "1985-2023",
    Categories: "Hepatology (Q1)",
    Areas: "Medicine",
  },
  {
    Rank: "79",
    Sourceid: "19700188417",
    Title: "Annual Review of Condensed Matter Physics",
    Type: "journal",
    Issn: "19475454, 19475462",
    SJR: "9,821",
    "SJR Best Quartile": "Q1",
    "H index": "87",
    "Total Docs. (2023)": "19",
    "Total Docs. (3years)": "55",
    "Total Refs.": "3059",
    "Total Cites (3years)": "1219",
    "Citable Docs. (3years)": "55",
    "Cites / Doc. (2years)": "15,56",
    "Ref. / Doc.": "161,00",
    "%Female": "15,38",
    Overton: "0",
    SDG: "1",
    Country: "United States",
    Region: "Northern America",
    Publisher: "Annual Reviews Inc.",
    Coverage: "2010-2023",
    Categories:
      "Condensed Matter Physics (Q1); Materials Science (miscellaneous) (Q1)",
    Areas: "Materials Science; Physics and Astronomy",
  },
  {
    Rank: "80",
    Sourceid: "16801",
    Title: "Annual Review of Biochemistry",
    Type: "journal",
    Issn: "15454509, 00664154",
    SJR: "9,745",
    "SJR Best Quartile": "Q1",
    "H index": "321",
    "Total Docs. (2023)": "17",
    "Total Docs. (3years)": "93",
    "Total Refs.": "2560",
    "Total Cites (3years)": "1605",
    "Citable Docs. (3years)": "93",
    "Cites / Doc. (2years)": "12,75",
    "Ref. / Doc.": "150,59",
    "%Female": "36,96",
    Overton: "0",
    SDG: "2",
    Country: "United States",
    Region: "Northern America",
    Publisher: "Annual Reviews Inc.",
    Coverage: "1946-1948, 1950-1960, 1962-2023",
    Categories: "Biochemistry (Q1)",
    Areas: "Biochemistry, Genetics and Molecular Biology",
  },
  {
    Rank: "81",
    Sourceid: "17700156208",
    Title: "Nature Reviews Gastroenterology and Hepatology",
    Type: "journal",
    Issn: "17595045, 17595053",
    SJR: "9,741",
    "SJR Best Quartile": "Q1",
    "H index": "193",
    "Total Docs. (2023)": "155",
    "Total Docs. (3years)": "459",
    "Total Refs.": "9634",
    "Total Cites (3years)": "9010",
    "Citable Docs. (3years)": "283",
    "Cites / Doc. (2years)": "17,88",
    "Ref. / Doc.": "62,15",
    "%Female": "33,84",
    Overton: "0",
    SDG: "44",
    Country: "United Kingdom",
    Region: "Western Europe",
    Publisher: "Nature Publishing Group",
    Coverage: "2009-2023",
    Categories: "Gastroenterology (Q1); Hepatology (Q1)",
    Areas: "Medicine",
  },
  {
    Rank: "82",
    Sourceid: "26756",
    Title: "Astronomy and Astrophysics Review",
    Type: "journal",
    Issn: "09354956, 14320754",
    SJR: "9,664",
    "SJR Best Quartile": "Q1",
    "H index": "78",
    "Total Docs. (2023)": "5",
    "Total Docs. (3years)": "24",
    "Total Refs.": "2659",
    "Total Cites (3years)": "622",
    "Citable Docs. (3years)": "24",
    "Cites / Doc. (2years)": "26,00",
    "Ref. / Doc.": "531,80",
    "%Female": "16,67",
    Overton: "0",
    SDG: "1",
    Country: "Germany",
    Region: "Western Europe",
    Publisher: "Springer Verlag",
    Coverage: "1989-2000, 2002-2004, 2006-2023",
    Categories:
      "Astronomy and Astrophysics (Q1); Space and Planetary Science (Q1)",
    Areas: "Earth and Planetary Sciences; Physics and Astronomy",
  },
  {
    Rank: "83",
    Sourceid: "20313",
    Title: "Nature Reviews Microbiology",
    Type: "journal",
    Issn: "17401534, 17401526",
    SJR: "9,639",
    "SJR Best Quartile": "Q1",
    "H index": "372",
    "Total Docs. (2023)": "173",
    "Total Docs. (3years)": "503",
    "Total Refs.": "9764",
    "Total Cites (3years)": "12098",
    "Citable Docs. (3years)": "361",
    "Cites / Doc. (2years)": "26,41",
    "Ref. / Doc.": "56,44",
    "%Female": "34,39",
    Overton: "8",
    SDG: "38",
    Country: "United Kingdom",
    Region: "Western Europe",
    Publisher: "Nature Publishing Group",
    Coverage: "2003-2023",
    Categories:
      "Immunology and Microbiology (miscellaneous)  (Q1); Infectious Diseases (Q1); Microbiology (Q1)",
    Areas: "Immunology and Microbiology; Medicine",
  },
  {
    Rank: "84",
    Sourceid: "21101049051",
    Title: "Nature Reviews Earth and Environment",
    Type: "journal",
    Issn: "2662138X",
    SJR: "9,521",
    "SJR Best Quartile": "Q1",
    "H index": "67",
    "Total Docs. (2023)": "121",
    "Total Docs. (3years)": "345",
    "Total Refs.": "8513",
    "Total Cites (3years)": "7894",
    "Citable Docs. (3years)": "229",
    "Cites / Doc. (2years)": "20,41",
    "Ref. / Doc.": "70,36",
    "%Female": "34,66",
    Overton: "7",
    SDG: "30",
    Country: "Switzerland",
    Region: "Western Europe",
    Publisher: "Springer International Publishing",
    Coverage: "2020-2023",
    Categories:
      "Atmospheric Science (Q1); Earth-Surface Processes (Q1); Nature and Landscape Conservation (Q1); Pollution (Q1)",
    Areas: "Earth and Planetary Sciences; Environmental Science",
  },
  {
    Rank: "85",
    Sourceid: "13900",
    Title: "Cell Research",
    Type: "journal",
    Issn: "17487838, 10010602",
    SJR: "9,506",
    "SJR Best Quartile": "Q1",
    "H index": "216",
    "Total Docs. (2023)": "144",
    "Total Docs. (3years)": "457",
    "Total Refs.": "4762",
    "Total Cites (3years)": "7465",
    "Citable Docs. (3years)": "238",
    "Cites / Doc. (2years)": "12,65",
    "Ref. / Doc.": "33,07",
    "%Female": "37,70",
    Overton: "0",
    SDG: "28",
    Country: "United Kingdom",
    Region: "Western Europe",
    Publisher: "Nature Publishing Group",
    Coverage: "1996-2023",
    Categories: "Cell Biology (Q1); Molecular Biology (Q1)",
    Areas: "Biochemistry, Genetics and Molecular Biology",
  },
  {
    Rank: "86",
    Sourceid: "12010",
    Title: "Annual Review of Psychology",
    Type: "journal",
    Issn: "00664308, 15452085",
    SJR: "9,438",
    "SJR Best Quartile": "Q1",
    "H index": "279",
    "Total Docs. (2023)": "23",
    "Total Docs. (3years)": "84",
    "Total Refs.": "3671",
    "Total Cites (3years)": "2317",
    "Citable Docs. (3years)": "81",
    "Cites / Doc. (2years)": "27,02",
    "Ref. / Doc.": "159,61",
    "%Female": "47,06",
    Overton: "0",
    SDG: "5",
    Country: "United States",
    Region: "Northern America",
    Publisher: "Annual Reviews Inc.",
    Coverage: "1950-1958, 1960-1963, 1965-2023",
    Categories: "Psychology (miscellaneous) (Q1)",
    Areas: "Psychology",
  },
  {
    Rank: "87",
    Sourceid: "21100804406",
    Title: "Lancet Public Health, The",
    Type: "journal",
    Issn: "24682667",
    SJR: "9,434",
    "SJR Best Quartile": "Q1",
    "H index": "90",
    "Total Docs. (2023)": "165",
    "Total Docs. (3years)": "504",
    "Total Refs.": "4230",
    "Total Cites (3years)": "7588",
    "Citable Docs. (3years)": "218",
    "Cites / Doc. (2years)": "12,32",
    "Ref. / Doc.": "25,64",
    "%Female": "42,59",
    Overton: "0",
    SDG: "105",
    Country: "United Kingdom",
    Region: "Western Europe",
    Publisher: "Elsevier Ltd",
    Coverage: "2016-2023",
    Categories: "Public Health, Environmental and Occupational Health (Q1)",
    Areas: "Medicine",
  },
  {
    Rank: "88",
    Sourceid: "18606",
    Title: "Molecular Cell",
    Type: "journal",
    Issn: "10974164, 10972765",
    SJR: "9,332",
    "SJR Best Quartile": "Q1",
    "H index": "443",
    "Total Docs. (2023)": "388",
    "Total Docs. (3years)": "1261",
    "Total Refs.": "25235",
    "Total Cites (3years)": "14868",
    "Citable Docs. (3years)": "1093",
    "Cites / Doc. (2years)": "10,75",
    "Ref. / Doc.": "65,04",
    "%Female": "38,89",
    Overton: "0",
    SDG: "77",
    Country: "United States",
    Region: "Northern America",
    Publisher: "Cell Press",
    Coverage: "1997-2023",
    Categories: "Cell Biology (Q1); Molecular Biology (Q1)",
    Areas: "Biochemistry, Genetics and Molecular Biology",
  },
  {
    Rank: "89",
    Sourceid: "19881",
    Title: "Advanced Materials",
    Type: "journal",
    Issn: "09359648, 15214095",
    SJR: "9,191",
    "SJR Best Quartile": "Q1",
    "H index": "640",
    "Total Docs. (2023)": "2652",
    "Total Docs. (3years)": "4816",
    "Total Refs.": "205113",
    "Total Cites (3years)": "141178",
    "Citable Docs. (3years)": "4781",
    "Cites / Doc. (2years)": "28,44",
    "Ref. / Doc.": "77,34",
    "%Female": "32,35",
    Overton: "1",
    SDG: "971",
    Country: "United States",
    Region: "Northern America",
    Publisher: "Wiley-Blackwell",
    Coverage: "1989-2023",
    Categories:
      "Materials Science (miscellaneous) (Q1); Mechanical Engineering (Q1); Mechanics of Materials (Q1); Nanoscience and Nanotechnology (Q1)",
    Areas: "Engineering; Materials Science",
  },
  {
    Rank: "90",
    Sourceid: "28973",
    Title: "Journal of Econometrics",
    Type: "journal",
    Issn: "03044076, 18726895",
    SJR: "9,161",
    "SJR Best Quartile": "Q1",
    "H index": "188",
    "Total Docs. (2023)": "288",
    "Total Docs. (3years)": "472",
    "Total Refs.": "13566",
    "Total Cites (3years)": "3517",
    "Citable Docs. (3years)": "454",
    "Cites / Doc. (2years)": "9,30",
    "Ref. / Doc.": "47,10",
    "%Female": "19,93",
    Overton: "45",
    SDG: "44",
    Country: "Netherlands",
    Region: "Western Europe",
    Publisher: "Elsevier B.V.",
    Coverage: "1973-2023",
    Categories: "Economics and Econometrics (Q1)",
    Areas: "Economics, Econometrics and Finance",
  },
  {
    Rank: "91",
    Sourceid: "17700156773",
    Title: "Synthesis Lectures on Artificial Intelligence and Machine Learning",
    Type: "book series",
    Issn: "19394616, 19394608",
    SJR: "9,129",
    "SJR Best Quartile": "Q1",
    "H index": "30",
    "Total Docs. (2023)": "13",
    "Total Docs. (3years)": "37",
    "Total Refs.": "234",
    "Total Cites (3years)": "370",
    "Citable Docs. (3years)": "4",
    "Cites / Doc. (2years)": "0,36",
    "Ref. / Doc.": "18,00",
    "%Female": "0,00",
    Overton: "0",
    SDG: "1",
    Country: "United States",
    Region: "Northern America",
    Publisher: "Springer International Publishing",
    Coverage: "2009-2023",
    Categories: "Artificial Intelligence (Q1)",
    Areas: "Computer Science",
  },
  {
    Rank: "92",
    Sourceid: "21100786228",
    Title: "Lancet Gastroenterology and Hepatology, The",
    Type: "journal",
    Issn: "24681253",
    SJR: "8,957",
    "SJR Best Quartile": "Q1",
    "H index": "105",
    "Total Docs. (2023)": "235",
    "Total Docs. (3years)": "671",
    "Total Refs.": "4964",
    "Total Cites (3years)": "7447",
    "Citable Docs. (3years)": "255",
    "Cites / Doc. (2years)": "9,92",
    "Ref. / Doc.": "21,12",
    "%Female": "46,48",
    Overton: "0",
    SDG: "95",
    Country: "United Kingdom",
    Region: "Western Europe",
    Publisher: "Elsevier Ltd",
    Coverage: "2016-2023",
    Categories: "Gastroenterology (Q1); Hepatology (Q1)",
    Areas: "Medicine",
  },
  {
    Rank: "93",
    Sourceid: "19900191767",
    Title: "American Economic Journal: Applied Economics",
    Type: "journal",
    Issn: "19457790, 19457782",
    SJR: "8,933",
    "SJR Best Quartile": "Q1",
    "H index": "109",
    "Total Docs. (2023)": "54",
    "Total Docs. (3years)": "140",
    "Total Refs.": "3650",
    "Total Cites (3years)": "925",
    "Citable Docs. (3years)": "140",
    "Cites / Doc. (2years)": "5,20",
    "Ref. / Doc.": "67,59",
    "%Female": "25,19",
    Overton: "29",
    SDG: "32",
    Country: "United States",
    Region: "Northern America",
    Publisher: "American Economic Association",
    Coverage: "2009-2023",
    Categories: "Economics, Econometrics and Finance (miscellaneous) (Q1)",
    Areas: "Economics, Econometrics and Finance",
  },
  {
    Rank: "94",
    Sourceid: "19700200701",
    Title: "Annual Review of Economics",
    Type: "journal",
    Issn: "19411383, 19411391",
    SJR: "8,925",
    "SJR Best Quartile": "Q1",
    "H index": "76",
    "Total Docs. (2023)": "28",
    "Total Docs. (3years)": "88",
    "Total Refs.": "2805",
    "Total Cites (3years)": "730",
    "Citable Docs. (3years)": "88",
    "Cites / Doc. (2years)": "6,70",
    "Ref. / Doc.": "100,18",
    "%Female": "22,22",
    Overton: "8",
    SDG: "13",
    Country: "United States",
    Region: "Northern America",
    Publisher: "Annual Reviews Inc.",
    Coverage: "2010-2023",
    Categories: "Economics and Econometrics (Q1)",
    Areas: "Economics, Econometrics and Finance",
  },
  {
    Rank: "95",
    Sourceid: "24535",
    Title: "Acta Numerica",
    Type: "journal",
    Issn: "14740508, 09624929",
    SJR: "8,913",
    "SJR Best Quartile": "Q1",
    "H index": "85",
    "Total Docs. (2023)": "7",
    "Total Docs. (3years)": "19",
    "Total Refs.": "1443",
    "Total Cites (3years)": "372",
    "Citable Docs. (3years)": "19",
    "Cites / Doc. (2years)": "16,54",
    "Ref. / Doc.": "206,14",
    "%Female": "12,50",
    Overton: "0",
    SDG: "0",
    Country: "United Kingdom",
    Region: "Western Europe",
    Publisher: "Cambridge University Press",
    Coverage: "1992-2023",
    Categories: "Mathematics (miscellaneous) (Q1); Numerical Analysis (Q1)",
    Areas: "Mathematics",
  },
  {
    Rank: "96",
    Sourceid: "19014",
    Title: "Nature Cell Biology",
    Type: "journal",
    Issn: "14764679, 14657392",
    SJR: "8,913",
    "SJR Best Quartile": "Q1",
    "H index": "409",
    "Total Docs. (2023)": "240",
    "Total Docs. (3years)": "556",
    "Total Refs.": "9691",
    "Total Cites (3years)": "6540",
    "Citable Docs. (3years)": "421",
    "Cites / Doc. (2years)": "9,91",
    "Ref. / Doc.": "40,38",
    "%Female": "40,14",
    Overton: "2",
    SDG: "54",
    Country: "United Kingdom",
    Region: "Western Europe",
    Publisher: "Nature Publishing Group",
    Coverage: "1999-2023",
    Categories: "Cell Biology (Q1)",
    Areas: "Biochemistry, Genetics and Molecular Biology",
  },
  {
    Rank: "97",
    Sourceid: "28599",
    Title: "Reviews of Geophysics",
    Type: "journal",
    Issn: "19449208, 87551209",
    SJR: "8,853",
    "SJR Best Quartile": "Q1",
    "H index": "191",
    "Total Docs. (2023)": "16",
    "Total Docs. (3years)": "67",
    "Total Refs.": "6100",
    "Total Cites (3years)": "1852",
    "Citable Docs. (3years)": "65",
    "Cites / Doc. (2years)": "25,02",
    "Ref. / Doc.": "381,25",
    "%Female": "32,29",
    Overton: "0",
    SDG: "6",
    Country: "United States",
    Region: "Northern America",
    Publisher: "John Wiley and Sons Inc.",
    Coverage: "1963-2023",
    Categories: "Geophysics (Q1)",
    Areas: "Earth and Planetary Sciences",
  },
  {
    Rank: "98",
    Sourceid: "21101101215",
    Title: "Cell Genomics",
    Type: "journal",
    Issn: "2666979X",
    SJR: "8,807",
    "SJR Best Quartile": "Q1",
    "H index": "20",
    "Total Docs. (2023)": "140",
    "Total Docs. (3years)": "108",
    "Total Refs.": "9664",
    "Total Cites (3years)": "954",
    "Citable Docs. (3years)": "82",
    "Cites / Doc. (2years)": "8,83",
    "Ref. / Doc.": "69,03",
    "%Female": "38,63",
    Overton: "1",
    SDG: "42",
    Country: "United States",
    Region: "Northern America",
    Publisher: "Cell Press",
    Coverage: "2021-2023",
    Categories:
      "Biochemistry, Genetics and Molecular Biology (miscellaneous) (Q1); Genetics (Q1)",
    Areas: "Biochemistry, Genetics and Molecular Biology",
  },
  {
    Rank: "99",
    Sourceid: "22401",
    Title: "Journal of the American College of Cardiology",
    Type: "journal",
    Issn: "15583597, 07351097",
    SJR: "8,762",
    "SJR Best Quartile": "Q1",
    "H index": "493",
    "Total Docs. (2023)": "631",
    "Total Docs. (3years)": "2380",
    "Total Refs.": "15404",
    "Total Cites (3years)": "21232",
    "Citable Docs. (3years)": "1052",
    "Cites / Doc. (2years)": "8,22",
    "Ref. / Doc.": "24,41",
    "%Female": "31,41",
    Overton: "9",
    SDG: "253",
    Country: "United States",
    Region: "Northern America",
    Publisher: "Elsevier Inc.",
    Coverage: "1983-2023",
    Categories: "Cardiology and Cardiovascular Medicine (Q1)",
    Areas: "Medicine",
  },
  {
    Rank: "100",
    Sourceid: "21100860945",
    Title: "Science immunology",
    Type: "journal",
    Issn: "24709468",
    SJR: "8,761",
    "SJR Best Quartile": "Q1",
    "H index": "106",
    "Total Docs. (2023)": "152",
    "Total Docs. (3years)": "517",
    "Total Refs.": "9106",
    "Total Cites (3years)": "7832",
    "Citable Docs. (3years)": "497",
    "Cites / Doc. (2years)": "14,04",
    "Ref. / Doc.": "59,91",
    "%Female": "41,87",
    Overton: "1",
    SDG: "67",
    Country: "United States",
    Region: "Northern America",
    Publisher: "American Association for the Advancement of Science",
    Coverage: "2016-2023",
    Categories: "Immunology (Q1); Immunology and Allergy (Q1)",
    Areas: "Immunology and Microbiology; Medicine",
  },
  {
    Rank: "101",
    Sourceid: "13839",
    Title: "Annual Review of Fluid Mechanics",
    Type: "book series",
    Issn: "15454479, 00664189",
    SJR: "8,751",
    "SJR Best Quartile": "Q1",
    "H index": "214",
    "Total Docs. (2023)": "27",
    "Total Docs. (3years)": "60",
    "Total Refs.": "3340",
    "Total Cites (3years)": "1757",
    "Citable Docs. (3years)": "59",
    "Cites / Doc. (2years)": "25,36",
    "Ref. / Doc.": "123,70",
    "%Female": "18,75",
    Overton: "0",
    SDG: "2",
    Country: "United States",
    Region: "Northern America",
    Publisher: "Annual Reviews Inc.",
    Coverage: "1970-1971, 1973-2011, 2013-2023",
    Categories: "Condensed Matter Physics (Q1)",
    Areas: "Physics and Astronomy",
  },
  {
    Rank: "102",
    Sourceid: "21100199127",
    Title: "Advanced Energy Materials",
    Type: "journal",
    Issn: "16146832, 16146840",
    SJR: "8,748",
    "SJR Best Quartile": "Q1",
    "H index": "319",
    "Total Docs. (2023)": "979",
    "Total Docs. (3years)": "2210",
    "Total Refs.": "75985",
    "Total Cites (3years)": "59605",
    "Citable Docs. (3years)": "2195",
    "Cites / Doc. (2years)": "25,38",
    "Ref. / Doc.": "77,61",
    "%Female": "30,16",
    Overton: "2",
    SDG: "635",
    Country: "Germany",
    Region: "Western Europe",
    Publisher: "John Wiley and Sons Inc.",
    Coverage: "2011-2023",
    Categories:
      "Materials Science (miscellaneous) (Q1); Renewable Energy, Sustainability and the Environment (Q1)",
    Areas: "Energy; Materials Science",
  },
  {
    Rank: "103",
    Sourceid: "21100888816",
    Title: "Signal Transduction and Targeted Therapy",
    Type: "journal",
    Issn: "20593635, 20959907",
    SJR: "8,737",
    "SJR Best Quartile": "Q1",
    "H index": "117",
    "Total Docs. (2023)": "457",
    "Total Docs. (3years)": "1105",
    "Total Refs.": "58854",
    "Total Cites (3years)": "23888",
    "Citable Docs. (3years)": "665",
    "Cites / Doc. (2years)": "20,66",
    "Ref. / Doc.": "128,78",
    "%Female": "41,19",
    Overton: "2",
    SDG: "263",
    Country: "United Kingdom",
    Region: "Western Europe",
    Publisher: "Springer Nature",
    Coverage: "2016-2023",
    Categories: "Cancer Research (Q1); Genetics (Q1)",
    Areas: "Biochemistry, Genetics and Molecular Biology",
  },
  {
    Rank: "104",
    Sourceid: "21100228100",
    Title: "Advances in Optics and Photonics",
    Type: "journal",
    Issn: "19438206",
    SJR: "8,735",
    "SJR Best Quartile": "Q1",
    "H index": "88",
    "Total Docs. (2023)": "14",
    "Total Docs. (3years)": "41",
    "Total Refs.": "4278",
    "Total Cites (3years)": "1198",
    "Citable Docs. (3years)": "38",
    "Cites / Doc. (2years)": "25,25",
    "Ref. / Doc.": "305,57",
    "%Female": "12,66",
    Overton: "0",
    SDG: "3",
    Country: "United States",
    Region: "Northern America",
    Publisher: "Optica Publishing Group (formerly OSA)",
    Coverage: "2009-2023",
    Categories:
      "Atomic and Molecular Physics, and Optics (Q1); Water Science and Technology (Q1)",
    Areas: "Environmental Science; Physics and Astronomy",
  },
  {
    Rank: "105",
    Sourceid: "18902",
    Title: "IEEE Journal on Selected Areas in Communications",
    Type: "journal",
    Issn: "07338716",
    SJR: "8,707",
    "SJR Best Quartile": "Q1",
    "H index": "263",
    "Total Docs. (2023)": "271",
    "Total Docs. (3years)": "724",
    "Total Refs.": "12672",
    "Total Cites (3years)": "11814",
    "Citable Docs. (3years)": "706",
    "Cites / Doc. (2years)": "14,83",
    "Ref. / Doc.": "46,76",
    "%Female": "26,38",
    Overton: "0",
    SDG: "32",
    Country: "United States",
    Region: "Northern America",
    Publisher: "Institute of Electrical and Electronics Engineers Inc.",
    Coverage: "1983-2023",
    Categories:
      "Computer Networks and Communications (Q1); Electrical and Electronic Engineering (Q1)",
    Areas: "Computer Science; Engineering",
  },
  {
    Rank: "106",
    Sourceid: "14181",
    Title: "Annual Review of Neuroscience",
    Type: "journal",
    Issn: "0147006X, 15454126",
    SJR: "8,658",
    "SJR Best Quartile": "Q1",
    "H index": "261",
    "Total Docs. (2023)": "20",
    "Total Docs. (3years)": "76",
    "Total Refs.": "2705",
    "Total Cites (3years)": "1168",
    "Citable Docs. (3years)": "76",
    "Cites / Doc. (2years)": "13,12",
    "Ref. / Doc.": "135,25",
    "%Female": "40,00",
    Overton: "0",
    SDG: "1",
    Country: "United States",
    Region: "Northern America",
    Publisher: "Annual Reviews Inc.",
    Coverage: "1978-2023",
    Categories: "Neuroscience (miscellaneous) (Q1)",
    Areas: "Neuroscience",
  },
  {
    Rank: "107",
    Sourceid: "21101151587",
    Title: "eLight",
    Type: "journal",
    Issn: "26628643, 20971710",
    SJR: "8,650",
    "SJR Best Quartile": "Q1",
    "H index": "22",
    "Total Docs. (2023)": "24",
    "Total Docs. (3years)": "30",
    "Total Refs.": "1592",
    "Total Cites (3years)": "774",
    "Citable Docs. (3years)": "29",
    "Cites / Doc. (2years)": "25,80",
    "Ref. / Doc.": "66,33",
    "%Female": "25,00",
    Overton: "0",
    SDG: "3",
    Country: "Singapore",
    Region: "Asiatic Region",
    Publisher: "Springer",
    Coverage: "2021-2023",
    Categories:
      "Atomic and Molecular Physics, and Optics (Q1); Electronic, Optical and Magnetic Materials (Q1)",
    Areas: "Materials Science; Physics and Astronomy",
  },
  {
    Rank: "108",
    Sourceid: "16860",
    Title: "Lancet Neurology, The",
    Type: "journal",
    Issn: "14744465, 14744422",
    SJR: "8,589",
    "SJR Best Quartile": "Q1",
    "H index": "355",
    "Total Docs. (2023)": "276",
    "Total Docs. (3years)": "802",
    "Total Refs.": "5512",
    "Total Cites (3years)": "9503",
    "Citable Docs. (3years)": "330",
    "Cites / Doc. (2years)": "10,24",
    "Ref. / Doc.": "19,97",
    "%Female": "42,69",
    Overton: "0",
    SDG: "49",
    Country: "United Kingdom",
    Region: "Western Europe",
    Publisher: "Elsevier Ltd",
    Coverage: "2002-2023",
    Categories: "Neurology (clinical) (Q1)",
    Areas: "Medicine",
  },
  {
    Rank: "109",
    Sourceid: "22581",
    Title: "Circulation",
    Type: "journal",
    Issn: "00097322, 15244539",
    SJR: "8,415",
    "SJR Best Quartile": "Q1",
    "H index": "674",
    "Total Docs. (2023)": "539",
    "Total Docs. (3years)": "2028",
    "Total Refs.": "16395",
    "Total Cites (3years)": "27681",
    "Citable Docs. (3years)": "1313",
    "Cites / Doc. (2years)": "13,29",
    "Ref. / Doc.": "30,42",
    "%Female": "34,11",
    Overton: "0",
    SDG: "226",
    Country: "United States",
    Region: "Northern America",
    Publisher: "Lippincott Williams and Wilkins Ltd.",
    Coverage: "1950-2023",
    Categories:
      "Cardiology and Cardiovascular Medicine (Q1); Physiology (medical) (Q1)",
    Areas: "Medicine",
  },
  {
    Rank: "110",
    Sourceid: "13443",
    Title: "Psychological Bulletin",
    Type: "journal",
    Issn: "00332909, 19391455",
    SJR: "8,412",
    "SJR Best Quartile": "Q1",
    "H index": "359",
    "Total Docs. (2023)": "23",
    "Total Docs. (3years)": "108",
    "Total Refs.": "4948",
    "Total Cites (3years)": "2752",
    "Citable Docs. (3years)": "107",
    "Cites / Doc. (2years)": "18,32",
    "Ref. / Doc.": "215,13",
    "%Female": "62,63",
    Overton: "1",
    SDG: "6",
    Country: "United States",
    Region: "Northern America",
    Publisher: "American Psychological Association",
    Coverage: "1904-2023",
    Categories:
      "History and Philosophy of Science (Q1); Psychology (miscellaneous) (Q1)",
    Areas: "Arts and Humanities; Psychology",
  },
  {
    Rank: "111",
    Sourceid: "17700156509",
    Title: "Nature Reviews Cardiology",
    Type: "journal",
    Issn: "17595010, 17595002",
    SJR: "8,408",
    "SJR Best Quartile": "Q1",
    "H index": "183",
    "Total Docs. (2023)": "153",
    "Total Docs. (3years)": "497",
    "Total Refs.": "10482",
    "Total Cites (3years)": "7493",
    "Citable Docs. (3years)": "251",
    "Cites / Doc. (2years)": "14,28",
    "Ref. / Doc.": "68,51",
    "%Female": "26,47",
    Overton: "2",
    SDG: "49",
    Country: "United Kingdom",
    Region: "Western Europe",
    Publisher: "Nature Publishing Group",
    Coverage: "2009-2023",
    Categories: "Cardiology and Cardiovascular Medicine (Q1)",
    Areas: "Medicine",
  },
  {
    Rank: "112",
    Sourceid: "29838",
    Title: "Journal of Accounting and Economics",
    Type: "journal",
    Issn: "01654101",
    SJR: "8,337",
    "SJR Best Quartile": "Q1",
    "H index": "187",
    "Total Docs. (2023)": "63",
    "Total Docs. (3years)": "137",
    "Total Refs.": "3951",
    "Total Cites (3years)": "1052",
    "Citable Docs. (3years)": "135",
    "Cites / Doc. (2years)": "5,81",
    "Ref. / Doc.": "62,71",
    "%Female": "21,92",
    Overton: "1",
    SDG: "13",
    Country: "Netherlands",
    Region: "Western Europe",
    Publisher: "Elsevier B.V.",
    Coverage: "1979-2023",
    Categories:
      "Accounting (Q1); Economics and Econometrics (Q1); Finance (Q1)",
    Areas:
      "Business, Management and Accounting; Economics, Econometrics and Finance",
  },
];

function JournalTable() {
  const [page, setPage] = useState(0);
  const [rowsPerPage, setRowsPerPage] = useState(25);
  const [selectedRow, setSelectedRow] = useState(null); // Track selected row for popover
  const [anchorEl, setAnchorEl] = useState(null); // Anchor element for popover positioning

  const handleChangePage = (event, newPage) => {
    setPage(newPage);
    setSelectedRow(null); // Reset selected row when changing page
  };

  const handleChangeRowsPerPage = (event) => {
    setRowsPerPage(parseInt(event.target.value, 10));
    setPage(0);
    setSelectedRow(null); // Reset selected row when changing rows per page
  };

  const handleRowClick = (event, row) => {
    setSelectedRow(row);
    setAnchorEl(event.currentTarget);
  };

  const handlePopoverClose = () => {
    setSelectedRow(null);
    setAnchorEl(null);
  };

  const open = Boolean(anchorEl);

  return (
    <Grid container spacing={2} justifyContent="center">
      <Grid item xs={12} md={10} lg={8}>
        <TableContainer
          component={Paper}
          sx={{ maxWidth: "100%", marginBottom: 2 }}
        >
          <Table sx={{ minWidth: 500 }}>
            <TableHead>
              <TableRow>
                <TableCell>Rank</TableCell>
                <TableCell>Title</TableCell>
                <TableCell>Type</TableCell>
                <TableCell>ISSN</TableCell>
                <TableCell>SJR</TableCell>
                <TableCell>SJR Best Quartile</TableCell>
                <TableCell>H Index</TableCell>
                <TableCell>Total Docs (2023)</TableCell>
                <TableCell>Total Docs (3 years)</TableCell>
                <TableCell>Total Refs</TableCell>
                <TableCell>Total Cites (3 years)</TableCell>
                <TableCell>Citable Docs (3 years)</TableCell>
                <TableCell>Cites / Doc (2 years)</TableCell>
                <TableCell>Ref. / Doc</TableCell>
                <TableCell>% Female</TableCell>
                <TableCell>Overton</TableCell>
                <TableCell>SDG</TableCell>
                <TableCell>Country</TableCell>
                <TableCell>Region</TableCell>
                <TableCell>Publisher</TableCell>
                <TableCell>Coverage</TableCell>
                <TableCell>Categories</TableCell>
                <TableCell>Areas</TableCell>
              </TableRow>
            </TableHead>
            <TableBody>
              {data
                .slice(page * rowsPerPage, page * rowsPerPage + rowsPerPage)
                .map((row, index) => (
                  <TableRow
                    key={index}
                    onClick={(e) => handleRowClick(e, row)}
                    sx={{
                      cursor: "pointer",
                      backgroundColor: index % 2 === 0 ? "#f0f8ff" : "white",
                    }}
                  >
                    <TableCell>{row.Rank}</TableCell>
                    <TableCell>{row.Title}</TableCell>
                    <TableCell>{row.Type}</TableCell>
                    <TableCell>{row.ISSN}</TableCell>
                    <TableCell>{row.SJR}</TableCell>
                    <TableCell>{row["SJR Best Quartile"]}</TableCell>
                    <TableCell>{row["H index"]}</TableCell>
                    <TableCell>{row["Total Docs. (2023)"]}</TableCell>
                    <TableCell>{row["Total Docs. (3years)"]}</TableCell>
                    <TableCell>{row["Total Refs."]}</TableCell>
                    <TableCell>{row["Total Cites (3years)"]}</TableCell>
                    <TableCell>{row["Citable Docs. (3years)"]}</TableCell>
                    <TableCell>{row["Cites / Doc. (2years)"]}</TableCell>
                    <TableCell>{row["Ref. / Doc."]}</TableCell>
                    <TableCell>{row["%Female"]}</TableCell>
                    <TableCell>{row.Overton}</TableCell>
                    <TableCell>{row.SDG}</TableCell>
                    <TableCell>{row.Country}</TableCell>
                    <TableCell>{row.Region}</TableCell>
                    <TableCell>{row.Publisher}</TableCell>
                    <TableCell>{row.Coverage}</TableCell>
                    <TableCell>{row.Categories}</TableCell>
                    <TableCell>{row.Areas}</TableCell>
                  </TableRow>
                ))}
            </TableBody>
          </Table>
        </TableContainer>
        <TablePagination
          rowsPerPageOptions={[25, 50, 75, 100]} // Customize rows per page options
          component="div"
          count={data.length} // Total number of rows
          rowsPerPage={rowsPerPage}
          page={page}
          onPageChange={handleChangePage}
          onRowsPerPageChange={handleChangeRowsPerPage}
        />

        {/* Popover for detailed view */}
        <Popover
          open={open}
          anchorEl={anchorEl}
          onClose={handlePopoverClose}
          anchorOrigin={{
            vertical: "center",
            horizontal: "center",
          }}
          transformOrigin={{
            vertical: "center",
            display: "center",
            horizontal: "center",
          }}
          PaperProps={{
            sx: {
              maxWidth: "90vw",
              maxHeight: "90vh",
              width: "80%", // Adjust card width as needed
              fontSize: "0.2rem", // Adjust font size for content
              overflow: "auto",
              p: 2,
            },
          }}
        >
          {selectedRow && (
            <Box>
              <Typography variant="h6" gutterBottom>
                {selectedRow.Title}
              </Typography>
              <Divider sx={{ marginBottom: 1 }} />
              <Grid container spacing={1}>
                <Grid item xs={6}>
                  <Typography variant="body2">
                    <strong>Rank:</strong> {selectedRow.Rank}
                  </Typography>
                  <Typography variant="body2">
                    <strong>Type:</strong> {selectedRow.Type}
                  </Typography>
                  <Typography variant="body2">
                    <strong>ISSN:</strong> {selectedRow.ISSN}
                  </Typography>
                  <Typography variant="body2">
                    <strong>SJR:</strong> {selectedRow.SJR}
                  </Typography>
                  <Typography variant="body2">
                    <strong>SJR Best Quartile:</strong>{" "}
                    {selectedRow["SJR Best Quartile"]}
                  </Typography>
                  <Typography variant="body2">
                    <strong>H Index:</strong> {selectedRow["H index"]}
                  </Typography>
                  <Typography variant="body2">
                    <strong>Total Docs (2023):</strong>{" "}
                    {selectedRow["Total Docs. (2023)"]}
                  </Typography>
                  <Typography variant="body2">
                    <strong>Total Docs (3 years):</strong>{" "}
                    {selectedRow["Total Docs. (3years)"]}
                  </Typography>
                  <Typography variant="body2">
                    <strong>Total Refs:</strong> {selectedRow["Total Refs."]}
                  </Typography>
                  <Typography variant="body2">
                    <strong>Total Cites (3 years):</strong>{" "}
                    {selectedRow["Total Cites (3years)"]}
                  </Typography>
                </Grid>
                <Grid item xs={6}>
                  <Typography variant="body2">
                    <strong>Citable Docs (3 years):</strong>{" "}
                    {selectedRow["Citable Docs. (3years)"]}
                  </Typography>
                  <Typography variant="body2">
                    <strong>Cites / Doc (2 years):</strong>{" "}
                    {selectedRow["Cites / Doc. (2years)"]}
                  </Typography>
                  <Typography variant="body2">
                    <strong>Ref. / Doc:</strong> {selectedRow["Ref. / Doc."]}
                  </Typography>
                  <Typography variant="body2">
                    <strong>% Female:</strong> {selectedRow["%Female"]}
                  </Typography>
                  <Typography variant="body2">
                    <strong>Overton:</strong> {selectedRow.Overton}
                  </Typography>
                  <Typography variant="body2">
                    <strong>SDG:</strong> {selectedRow.SDG}
                  </Typography>
                  <Typography variant="body2">
                    <strong>Country:</strong> {selectedRow.Country}
                  </Typography>
                  <Typography variant="body2">
                    <strong>Region:</strong> {selectedRow.Region}
                  </Typography>
                  <Typography variant="body2">
                    <strong>Publisher:</strong> {selectedRow.Publisher}
                  </Typography>
                  <Typography variant="body2">
                    <strong>Coverage:</strong> {selectedRow.Coverage}
                  </Typography>
                  <Typography variant="body2">
                    <strong>Categories:</strong> {selectedRow.Categories}
                  </Typography>
                  <Typography variant="body2">
                    <strong>Areas:</strong> {selectedRow.Areas}
                  </Typography>
                </Grid>
              </Grid>
            </Box>
          )}
        </Popover>
      </Grid>
    </Grid>
  );
}

export default JournalTable;
